<?php
// Read-only, aggregate-only WP-CLI helper. Never prints identifiers or rows.
if (!defined('WP_CLI') || !WP_CLI) { exit(1); }
global $wpdb;
$table = function ($suffix) use ($wpdb) { return $wpdb->prefix . 'nmkr_' . $suffix; };
$count = function ($sql) use ($wpdb) { $wpdb->last_error=''; $v=$wpdb->get_var($sql); if($wpdb->last_error!==''||$v===null){WP_CLI::error('Synthetic state query failed.',false);exit(1);} return (int)$v; };
$projects=$table('projects'); $tokens=$table('tokens'); $details=$table('token_details'); $history=$table('sync_stats'); $metrics=$table('sync_metrics');
$row = function ($sql) use ($wpdb) { $wpdb->last_error=''; $v=$wpdb->get_row($sql,ARRAY_A); if($wpdb->last_error!==''){WP_CLI::error('Synthetic state query failed.',false);exit(1);} return is_array($v)?$v:array(); };
$hooks=array('nmkr_execute_sync_background','nmkr_process_batch_hook','nmkr_resume_sync_finalization'); $cron=array(); foreach($hooks as $hook){$cron[$hook]=0;} foreach((array)_get_cron_array() as $events){foreach($hooks as $hook){if(isset($events[$hook]))$cron[$hook]+=count($events[$hook]);}}
$provider=json_decode((string)@file_get_contents((string)getenv('NMKR_SYNTHETIC_STATE_FILE')),true);
$history_latest=$row("SELECT id,status,items_processed,items_successful,items_failed,(end_time IS NOT NULL) AS ended,(error_message IS NULL OR error_message='') AS error_free FROM `$history` ORDER BY id DESC LIMIT 1");
$metrics_latest=$row("SELECT id,total_projects,total_tokens,total_sync_duration,total_api_time,average_response_time,api_requests,memory_usage,(last_sync_time IS NOT NULL) AS timestamped FROM `$metrics` ORDER BY id DESC LIMIT 1");
$history_latest=array('id'=>(int)($history_latest['id']??0),'status'=>(string)($history_latest['status']??''),'items_processed'=>(int)($history_latest['items_processed']??0),'items_successful'=>(int)($history_latest['items_successful']??0),'items_failed'=>(int)($history_latest['items_failed']??0),'ended'=>(int)($history_latest['ended']??0),'error_free'=>(int)($history_latest['error_free']??0));
$metrics_latest=array('id'=>(int)($metrics_latest['id']??0),'total_projects'=>(int)($metrics_latest['total_projects']??0),'total_tokens'=>(int)($metrics_latest['total_tokens']??0),'total_sync_duration'=>(float)($metrics_latest['total_sync_duration']??0),'total_api_time'=>(float)($metrics_latest['total_api_time']??0),'average_response_time'=>(float)($metrics_latest['average_response_time']??0),'api_requests'=>(int)($metrics_latest['api_requests']??0),'memory_usage'=>(float)($metrics_latest['memory_usage']??0),'timestamped'=>(int)($metrics_latest['timestamped']??0));
$chains=array('cardano_only'=>$count("SELECT COUNT(*) FROM `$projects` WHERE project_uid LIKE 'synthetic-project-%' AND blockchains='[\"Cardano\"]' AND (solana_project_details IS NULL OR solana_project_details='')"),'solana_only'=>$count("SELECT COUNT(*) FROM `$projects` WHERE project_uid LIKE 'synthetic-project-%' AND blockchains='[\"Solana\"]' AND solana_project_details<>''"),'dual_chain'=>$count("SELECT COUNT(*) FROM `$projects` WHERE project_uid LIKE 'synthetic-project-%' AND blockchains='[\"Cardano\",\"Solana\"]' AND solana_project_details<>''"));
$out=array('schema_version'=>2,'project_count'=>$count("SELECT COUNT(*) FROM `$projects` WHERE project_uid LIKE 'synthetic-project-%'"),'token_count'=>$count("SELECT COUNT(*) FROM `$tokens` WHERE token_uid LIKE 'synthetic-project-%-token-%'"),'token_detail_count'=>$count("SELECT COUNT(*) FROM `$details` d INNER JOIN `$tokens` t ON t.token_uid=d.token_uid WHERE t.token_uid LIKE 'synthetic-project-%-token-%'"),'chain_classifications'=>$chains,'duplicate_project_count'=>$count("SELECT COUNT(*) FROM (SELECT project_uid FROM `$projects` WHERE project_uid LIKE 'synthetic-project-%' GROUP BY project_uid HAVING COUNT(*)>1) x"),'duplicate_token_count'=>$count("SELECT COUNT(*) FROM (SELECT token_uid FROM `$tokens` WHERE token_uid LIKE 'synthetic-project-%-token-%' GROUP BY token_uid HAVING COUNT(*)>1) x"),'orphan_token_count'=>$count("SELECT COUNT(*) FROM `$tokens` t LEFT JOIN `$projects` p ON p.project_uid=t.project_uid WHERE t.token_uid LIKE 'synthetic-project-%-token-%' AND p.project_uid IS NULL"),'orphan_detail_count'=>$count("SELECT COUNT(*) FROM `$details` d LEFT JOIN `$tokens` t ON t.token_uid=d.token_uid WHERE d.token_uid LIKE 'synthetic-project-%-token-%' AND t.token_uid IS NULL"),'history_count'=>$count("SELECT COUNT(*) FROM `$history`"),'history_max_id'=>$count("SELECT COALESCE(MAX(id),0) FROM `$history`"),'latest_history'=>$history_latest,'active_history_count'=>$count("SELECT COUNT(*) FROM `$history` WHERE status NOT IN ('completed','failed','stopped','cancelled') OR status IS NULL"),'metrics_count'=>$count("SELECT COUNT(*) FROM `$metrics`"),'metrics_max_id'=>$count("SELECT COALESCE(MAX(id),0) FROM `$metrics`"),'latest_metrics'=>$metrics_latest,'owner_present'=>(bool)get_option('nmkr_sync_owner',false),'active_marker'=>(bool)get_option('nmkr_sync_in_progress',false),'worker_lock'=>(bool)get_transient('nmkr_sync_worker_lock'),'heartbeat'=>(bool)get_option('nmkr_sync_heartbeat',false),'live_metrics'=>(bool)get_transient('nmkr_current_sync_stats_live'),'cron'=>$cron,'provider_counters'=>is_array($provider)&&isset($provider['counters'])?$provider['counters']:null);
WP_CLI::line(wp_json_encode($out));
