<?php
/** Public-safe deterministic HTTP attempt and metric regression. */
define('ABSPATH', dirname(__DIR__) . '/'); define('HOUR_IN_SECONDS', 3600); define('NMKR_SYNC_TRANSIENT_TTL', 3600);
class WP_Error { private $c; private $m; function __construct($c,$m='',$d=null){$this->c=$c;$this->m=$m;} function get_error_code(){return $this->c;} function get_error_message(){return $this->m;} }
function is_wp_error($v){return $v instanceof WP_Error;} function plugin_dir_path($f){return dirname($f).'/';}
$GLOBALS['tr']=array(); function get_transient($k){return $GLOBALS['tr'][$k]??false;} function set_transient($k,$v,$t){$GLOBALS['tr'][$k]=$v;return true;} function delete_transient($k){unset($GLOBALS['tr'][$k]);}
function get_option($k,$d=false){return $k==='nmkr_connect_options'?array('api_key'=>'synthetic-placeholder'):$d;}
function wp_remote_retrieve_body($r){return $r['body']??'';} function wp_remote_retrieve_response_code($r){return $r['code']??0;} function wp_remote_retrieve_header($r,$k){return $r['headers'][$k]??'';}
require dirname(__DIR__).'/includes/helpers/nmkr-performance-functions.php'; require dirname(__DIR__).'/includes/api/nmkr-api-functions.php';
function ok($v,$m){if(!$v){fwrite(STDERR,"FAIL: $m\n");exit(1);}echo "PASS: $m\n";}
function run_case($responses,$shape='nmkr_sync_list_shape',$checkpoint=null,$epoch=0.0){global $nmkr_api_call_times,$nmkr_api_rate_limited,$nmkr_api_cooldown_until;$nmkr_api_call_times=array();$nmkr_api_rate_limited=false;$nmkr_api_cooldown_until=0;$GLOBALS['tr']=array();$now=$epoch;$calls=0;$ctx=array('clock'=>function()use(&$now){return $now;},'sleep'=>function($s)use(&$now){$now+=$s;},'jitter'=>function(){return 0;},'request'=>function()use(&$responses,&$calls,&$now){$calls++;$now+=.25;return array_shift($responses);});if($checkpoint)$ctx['checkpoint']=$checkpoint;$result=nmkr_sync_http_json_execute('synthetic','https://public.invalid/synthetic',array(),$shape,$ctx);return array($result,$GLOBALS['tr']['nmkr_current_sync_stats_live']??array(),$calls,$now-$epoch);}
foreach(array(array('[]','nmkr_sync_list_shape','project list'),array('[{"uid":"synthetic"}]','nmkr_sync_list_shape','token list'),array('{"uid":"synthetic"}','nmkr_sync_detail_shape','token detail')) as $valid){list($r,$m)=run_case(array(array('code'=>200,'body'=>$valid[0])),$valid[1]);ok(is_array($r)&&$m['request_count']===1&&$m['successful_requests']===1,"valid {$valid[2]} counted once");}
foreach(array('', '{', '{}') as $body){list($r,$m)=run_case(array(array('code'=>200,'body'=>$body)));ok(is_wp_error($r)&&$m['failed_requests']===1,'empty, malformed, or wrong list shape fails');}
list($r,$m)=run_case(array(array('code'=>200,'body'=>'[]')),'nmkr_sync_detail_shape');ok(is_wp_error($r)&&$r->get_error_code()==='nmkr_api_invalid_shape','wrong detail shape fails');
foreach(array(401,403,404) as $status){list($r,$m,$calls)=run_case(array(array('code'=>$status,'body'=>'{}')));ok(is_wp_error($r)&&$calls===1&&$m['failed_requests']===1,"HTTP $status is non-retriable");}
foreach(array(408,500) as $status){list($r,$m)=run_case(array(array('code'=>$status,'body'=>'{}'),array('code'=>200,'body'=>'[]')));ok(is_array($r)&&$m['request_count']===2&&$m['retry_count']===1,"HTTP $status retries once then succeeds");}
list($r,$m,$calls,$elapsed)=run_case(array(array('code'=>429,'body'=>'{}','headers'=>array('retry-after'=>'2')),array('code'=>200,'body'=>'[]')));ok($calls===2&&$m['backoff_wait_duration']>=2&&$m['total_api_time']===.5&&$elapsed>=2.5,'integer Retry-After and backoff are excluded from network time');
$epoch=1700000000; $date=gmdate('D, d M Y H:i:s \G\M\T',$epoch+5);list($r,$m,$calls,$elapsed)=run_case(array(array('code'=>429,'body'=>'{}','headers'=>array('retry-after'=>$date)),array('code'=>200,'body'=>'[]')),'nmkr_sync_list_shape',null,$epoch);ok($calls===2&&abs($elapsed-5.25)<0.000001,'HTTP-date Retry-After uses injected clock deterministically');
list($r,$m)=run_case(array(new WP_Error('http_request_failed','timeout'),array('code'=>200,'body'=>'[]')));ok(is_array($r)&&$m['failed_requests']===1&&$m['successful_requests']===1,'transport timeout retries');
list($r,$m)=run_case(array(array('code'=>503,'body'=>'{}'),array('code'=>503,'body'=>'{}'),array('code'=>503,'body'=>'{}')));ok(is_wp_error($r)&&$r->get_error_code()==='nmkr_api_retry_exhausted'&&$m['request_count']===3&&$m['retry_count']===2,'retry exhaustion is bounded to three attempts');
$stop_backoff=function($phase){return $phase==='before_api_backoff_wait'?new WP_Error('sync_stop_requested','stop'):true;};list($r,$m,$calls)=run_case(array(array('code'=>500,'body'=>'{}'),array('code'=>200,'body'=>'[]')),'nmkr_sync_list_shape',$stop_backoff);ok(is_wp_error($r)&&$r->get_error_code()==='sync_stop_requested'&&$calls===1,'Stop during retry wait prevents another dispatch');
$owner_halt=function($phase){return $phase==='before_api_dispatch'?new WP_Error('sync_owner_mismatch','owner'):true;};list($r,$m,$calls)=run_case(array(array('code'=>200,'body'=>'[]')),'nmkr_sync_list_shape',$owner_halt);ok(is_wp_error($r)&&$r->get_error_code()==='sync_owner_mismatch'&&$calls===0&&empty($m['request_count']),'owner halt immediately before dispatch records no attempt');
list($r,$m)=run_case(array(array('code'=>408,'body'=>'{}'),array('code'=>200,'body'=>'[]')));ok($m['successful_requests']+$m['failed_requests']===$m['request_count']&&count($m['request_times'])===$m['request_count'],'attempt-accounting invariants hold');
// A real measured zero is a sample, not missing evidence.
list($r,$m)=run_case(array(array('code'=>200,'body'=>'[]')));$m['request_times']=array(0.0);$m['total_api_time']=0.0;ok($m['request_times'][0]===0.0,'measured zero duration remains valid');
echo "All HTTP and metric regressions passed.\n";
