<?php
/** Phase 16A read-only aggregate state snapshot. */
if (!defined('ABSPATH')) { fwrite(STDERR, "WordPress must be loaded.\n"); exit(1); }
global $wpdb;
function nmkr16_table_exists($table) { global $wpdb; return $wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s', $table)) === $table; }
function nmkr16_count($sql) { global $wpdb; $v = $wpdb->get_var($sql); return is_numeric($v) ? (int) $v : 0; }
function nmkr16_max($table) { global $wpdb; if (!nmkr16_table_exists($table)) return 0; $v = $wpdb->get_var("SELECT MAX(id) FROM `" . esc_sql($table) . "`"); return is_numeric($v) ? (int) $v : 0; }
function nmkr16_has_col($table, $col) { global $wpdb; return (bool) $wpdb->get_var($wpdb->prepare('SHOW COLUMNS FROM `' . esc_sql($table) . '` LIKE %s', $col)); }
function nmkr16_digest_terminal($table) { global $wpdb; if (!nmkr16_table_exists($table)) return hash('sha256', 'missing'); $limit = getenv('NMKR_PHASE16A_HISTORY_MAX_ID'); $limit_sql = (is_numeric($limit) && (int) $limit > 0) ? ' AND id <= ' . (int) $limit : ''; $rows = $wpdb->get_results("SELECT id,sync_type,start_time,end_time,status,items_processed,items_successful,items_failed,updated_at FROM `" . esc_sql($table) . "` WHERE BINARY status IN ('completed','success','failed','error','stopped','cancelled','aborted')" . $limit_sql . " ORDER BY id ASC", ARRAY_A); $ctx = hash_init('sha256'); foreach ((array) $rows as $row) { hash_update($ctx, hash('sha256', wp_json_encode($row)) . "\n"); } return hash_final($ctx); }
function nmkr16_option_truthy($name) { $v = get_option($name, null); return in_array($v, array(true, 1, '1', 'true', 'yes', 'on'), true); }
function nmkr16_transient_active_count() { $count = 0; foreach (array('nmkr_sync_in_progress','nmkr_sync_progress','nmkr_sync_active','nmkr_stale_sync_recovery') as $key) { $v = wp_using_ext_object_cache() ? get_transient($key) : get_option('_transient_' . $key, null); if (in_array($v, array(true, 1, '1', 'true', 'yes', 'on'), true) || (is_array($v) && !empty($v))) $count++; } return $count; }
$prefix = $wpdb->prefix;
$projects = $prefix . 'nmkr_projects'; $tokens = $prefix . 'nmkr_tokens'; $details = $prefix . 'nmkr_token_details'; $stats = $prefix . 'nmkr_sync_stats'; $metrics = $prefix . 'nmkr_sync_metrics';
$tables = array('projects'=>$projects,'tokens'=>$tokens,'token_details'=>$details,'sync_stats'=>$stats,'sync_metrics'=>$metrics);
$present = array(); foreach ($tables as $k=>$t) { $present[$k] = nmkr16_table_exists($t); }
$history_total = $present['sync_stats'] ? nmkr16_count("SELECT COUNT(*) FROM `" . esc_sql($stats) . "`") : 0;
$active_history = $present['sync_stats'] ? nmkr16_count("SELECT COUNT(*) FROM `" . esc_sql($stats) . "` WHERE BINARY status IN ('running','in_progress','processing','active','started') AND (end_time IS NULL OR end_time = '')") : 0;
$terminal_history = $present['sync_stats'] ? nmkr16_count("SELECT COUNT(*) FROM `" . esc_sql($stats) . "` WHERE BINARY status IN ('completed','success','failed','error','stopped','cancelled','aborted')") : 0;
$metrics_total = $present['sync_metrics'] ? nmkr16_count("SELECT COUNT(*) FROM `" . esc_sql($metrics) . "`") : 0;
$latest_metric = $present['sync_metrics'] ? (string) $wpdb->get_var("SELECT last_sync_time FROM `" . esc_sql($metrics) . "` ORDER BY last_sync_time DESC, id DESC LIMIT 1") : '';
$last_sync = (string) get_option('nmkr_last_sync_time', '');
$cron = get_option('cron'); $cron_ok = is_array($cron); $blocked = 0; if ($cron_ok) { foreach ($cron as $ts=>$hooks) { if (!is_array($hooks)) { $cron_ok = false; break; } if (isset($hooks['nmkr_execute_sync_background'])) $blocked += is_array($hooks['nmkr_execute_sync_background']) ? count($hooks['nmkr_execute_sync_background']) : 1; } }
$sync_data = get_option('nmkr_sync_data', null); $sync_data_class = 'absent'; if (is_array($sync_data)) { $status = isset($sync_data['status']) ? (string) $sync_data['status'] : ''; $sync_data_class = in_array($status, array('completed','success','failed','error','stopped','cancelled','aborted'), true) ? 'terminal' : 'active_or_unknown'; }
$dup_project = ($present['projects'] && nmkr16_has_col($projects,'project_uid')) ? nmkr16_count("SELECT COUNT(*) FROM (SELECT project_uid FROM `" . esc_sql($projects) . "` WHERE project_uid IS NOT NULL AND project_uid <> '' GROUP BY project_uid HAVING COUNT(*) > 1) d") : 0;
$dup_token = ($present['tokens'] && nmkr16_has_col($tokens,'token_uid')) ? nmkr16_count("SELECT COUNT(*) FROM (SELECT token_uid FROM `" . esc_sql($tokens) . "` WHERE token_uid IS NOT NULL AND token_uid <> '' GROUP BY token_uid HAVING COUNT(*) > 1) d") : 0;
$dup_detail = ($present['token_details'] && nmkr16_has_col($details,'token_uid')) ? nmkr16_count("SELECT COUNT(*) FROM (SELECT token_uid FROM `" . esc_sql($details) . "` WHERE token_uid IS NOT NULL AND token_uid <> '' GROUP BY token_uid HAVING COUNT(*) > 1) d") : 0;
$invalid_rel = ($present['tokens'] && $present['projects']) ? nmkr16_count("SELECT COUNT(*) FROM `" . esc_sql($tokens) . "` t LEFT JOIN `" . esc_sql($projects) . "` p ON t.project_uid=p.project_uid WHERE t.project_uid IS NOT NULL AND t.project_uid<>'' AND p.project_uid IS NULL") : 0;
$invalid_rel += ($present['token_details'] && $present['tokens']) ? nmkr16_count("SELECT COUNT(*) FROM `" . esc_sql($details) . "` d LEFT JOIN `" . esc_sql($tokens) . "` t ON d.token_uid=t.token_uid WHERE d.token_uid IS NOT NULL AND d.token_uid<>'' AND t.token_uid IS NULL") : 0;
$impossible = 0; if ($present['sync_stats']) $impossible += nmkr16_count("SELECT COUNT(*) FROM `" . esc_sql($stats) . "` WHERE start_time IS NULL OR items_processed < 0 OR items_successful < 0 OR items_failed < 0 OR (end_time IS NOT NULL AND end_time < start_time)"); if ($present['sync_metrics']) $impossible += nmkr16_count("SELECT COUNT(*) FROM `" . esc_sql($metrics) . "` WHERE total_projects < 0 OR total_tokens < 0 OR total_sync_duration < 0 OR total_api_time < 0 OR average_response_time < 0 OR api_requests < 0 OR memory_usage < 0 OR last_sync_time IS NULL");
$out = array('schema_version'=>1,'required_tables_present'=>$present,'project_count'=>$present['projects']?nmkr16_count("SELECT COUNT(*) FROM `".esc_sql($projects)."`"):0,'project_max_id'=>nmkr16_max($projects),'token_count'=>$present['tokens']?nmkr16_count("SELECT COUNT(*) FROM `".esc_sql($tokens)."`"):0,'token_max_id'=>nmkr16_max($tokens),'token_detail_count'=>$present['token_details']?nmkr16_count("SELECT COUNT(*) FROM `".esc_sql($details)."`"):0,'token_detail_max_id'=>nmkr16_max($details),'sync_history_total_count'=>$history_total,'active_history_count'=>$active_history,'terminal_history_count'=>$terminal_history,'max_history_id'=>nmkr16_max($stats),'metrics_total_count'=>$metrics_total,'max_metrics_id'=>nmkr16_max($metrics),'duplicate_project_uid_count'=>$dup_project,'duplicate_token_uid_count'=>$dup_token,'duplicate_token_detail_uid_count'=>$dup_detail,'invalid_relationship_count'=>$invalid_rel,'impossible_counter_count'=>$impossible,'option_active_marker_count'=>(nmkr16_option_truthy('nmkr_sync_in_progress')?1:0)+(nmkr16_option_truthy('nmkr_sync_active')?1:0),'transient_active_marker_count'=>nmkr16_transient_active_count(),'sync_data_classification'=>$sync_data_class,'blocked_sync_cron_count'=>$blocked,'cron_inspectable'=>$cron_ok,'light_profile_guard'=>get_option('nmkr_sync_profile','')==='light','api_key_present'=>get_option('nmkr_api_key','')!=='','last_sync_time_matches_latest_metrics'=>($last_sync===''&&$latest_metric==='')||($last_sync!==''&&$last_sync===$latest_metric),'terminal_history_digest_before'=>nmkr16_digest_terminal($stats),'latest_history_completed'=>($present['sync_stats'] ? (bool) $wpdb->get_var("SELECT COUNT(*) FROM `" . esc_sql($stats) . "` WHERE id = (SELECT MAX(id) FROM `" . esc_sql($stats) . "`) AND BINARY status IN ('completed','success') AND end_time IS NOT NULL AND end_time <> ''") : false),'snapshot_epoch'=>time());
echo wp_json_encode($out, JSON_UNESCAPED_SLASHES) . "\n";
