<?php
// Read-only, aggregate-only WP-CLI helper. Never prints identifiers or rows.
if (!defined('WP_CLI') || !WP_CLI) { exit(1); }
global $wpdb;
$table = function ($suffix) use ($wpdb) { return $wpdb->prefix . 'nmkr_' . $suffix; };
$count = function ($sql) use ($wpdb) { $wpdb->last_error=''; $v=$wpdb->get_var($sql); if($wpdb->last_error!==''||$v===null){WP_CLI::error('Synthetic state query failed.',false);exit(1);} return (int)$v; };
$projects=$table('projects'); $tokens=$table('tokens'); $details=$table('token_details'); $history=$table('sync_stats'); $metrics=$table('sync_metrics');
$hooks=array('nmkr_execute_sync_background','nmkr_process_batch_hook','nmkr_resume_sync_finalization'); $cron=array(); foreach($hooks as $hook){$cron[$hook]=0;} foreach((array)_get_cron_array() as $events){foreach($hooks as $hook){if(isset($events[$hook]))$cron[$hook]+=count($events[$hook]);}}
$provider=json_decode((string)@file_get_contents((string)getenv('NMKR_SYNTHETIC_STATE_FILE')),true);
$out=array('schema_version'=>1,'project_count'=>$count("SELECT COUNT(*) FROM `$projects` WHERE project_uid LIKE 'synthetic-project-%'"),'token_count'=>$count("SELECT COUNT(*) FROM `$tokens` WHERE token_uid LIKE 'synthetic-project-%-token-%'"),'token_detail_count'=>$count("SELECT COUNT(*) FROM `$details` d INNER JOIN `$tokens` t ON t.token_uid=d.token_uid WHERE t.token_uid LIKE 'synthetic-project-%-token-%'"),'duplicate_project_count'=>$count("SELECT COUNT(*) FROM (SELECT project_uid FROM `$projects` WHERE project_uid LIKE 'synthetic-project-%' GROUP BY project_uid HAVING COUNT(*)>1) x"),'duplicate_token_count'=>$count("SELECT COUNT(*) FROM (SELECT token_uid FROM `$tokens` WHERE token_uid LIKE 'synthetic-project-%-token-%' GROUP BY token_uid HAVING COUNT(*)>1) x"),'orphan_token_count'=>$count("SELECT COUNT(*) FROM `$tokens` t LEFT JOIN `$projects` p ON p.project_uid=t.project_uid WHERE t.token_uid LIKE 'synthetic-project-%-token-%' AND p.project_uid IS NULL"),'orphan_detail_count'=>$count("SELECT COUNT(*) FROM `$details` d LEFT JOIN `$tokens` t ON t.token_uid=d.token_uid WHERE d.token_uid LIKE 'synthetic-project-%-token-%' AND t.token_uid IS NULL"),'history_count'=>$count("SELECT COUNT(*) FROM `$history`"),'active_history_count'=>$count("SELECT COUNT(*) FROM `$history` WHERE status NOT IN ('completed','failed','stopped','cancelled') OR status IS NULL"),'metrics_count'=>$count("SELECT COUNT(*) FROM `$metrics`"),'owner_present'=>(bool)get_option('nmkr_sync_owner',false),'active_marker'=>(bool)get_option('nmkr_sync_in_progress',false),'worker_lock'=>(bool)get_transient('nmkr_sync_worker_lock'),'heartbeat'=>(bool)get_option('nmkr_sync_heartbeat',false),'live_metrics'=>(bool)get_transient('nmkr_current_sync_stats_live'),'cron'=>$cron,'provider_counters'=>is_array($provider)&&isset($provider['counters'])?$provider['counters']:null);
WP_CLI::line(wp_json_encode($out));
