<?php
// Public-safe synthetic lifecycle regression; no WordPress install or network access.
define('ABSPATH', __DIR__); define('NMKR_SYNC_TRANSIENT_TTL', 3600); define('ARRAY_A', 'ARRAY_A');
class WP_Error {private $code; private $message; function __construct($c='',$m=''){$this->code=$c;$this->message=$m;} function get_error_code(){return $this->code;} function get_error_message(){return $this->message;}} function is_wp_error($v){return $v instanceof WP_Error;} function __($text){return $text;}
function nmkr_is_valid_sync_run_id($v){return is_string($v)&&preg_match('/^[a-f0-9-]{36}$/',$v);}
$GLOBALS['options']=array(); $GLOBALS['transients']=array(); $GLOBALS['history']=array(); $GLOBALS['metrics']=array(); $GLOBALS['hooks']=array(); $GLOBALS['scheduled_delays']=array(); $GLOBALS['checkpoint']='';
function get_option($k,$d=false){return array_key_exists($k,$GLOBALS['options'])?$GLOBALS['options'][$k]:$d;} function update_option($k,$v){if(($GLOBALS['fail_cleanup']??'')==='option:'.$k)return false;$GLOBALS['options'][$k]=$v;return true;} function delete_option($k){if(($GLOBALS['fail_cleanup']??'')==='option:'.$k)return false;if($k==='nmkr_sync_owner')$GLOBALS['owner']=false;unset($GLOBALS['options'][$k]);return true;}
function get_transient($k){return array_key_exists($k,$GLOBALS['transients'])?$GLOBALS['transients'][$k]:false;} function set_transient($k,$v,$ttl){$GLOBALS['transients'][$k]=$v;return true;} function delete_transient($k){if(($GLOBALS['fail_cleanup']??'')==='transient:'.$k)return false;unset($GLOBALS['transients'][$k]);return true;}
function add_action(){} function hook_key($h,$a=array()){return $h.(!empty($a)?':'.implode(',',$a):'');} function wp_clear_scheduled_hook($h,$a=array()){if(($GLOBALS['fail_cleanup']??'')==='hook:'.$h)return false;unset($GLOBALS['hooks'][hook_key($h,$a)]);return 1;} function wp_next_scheduled($h,$a=array()){return isset($GLOBALS['hooks'][hook_key($h,$a)])?$GLOBALS['hooks'][hook_key($h,$a)]:false;} function wp_schedule_single_event($time,$h,$a=array()){if(!empty($GLOBALS['fail_schedule']))return false;$k=hook_key($h,$a);if(isset($GLOBALS['hooks'][$k]))return false;$GLOBALS['hooks'][$k]=$time;$GLOBALS['scheduled_delays'][]=$time-time();return true;} function maybe_serialize($v){return serialize($v);} function maybe_unserialize($v){return unserialize($v);} function wp_cache_delete(){}
function nmkr_get_timestamp(){return '2026-01-02 03:04:05';} function nmkr_get_sync_data(){return get_option('nmkr_sync_data',array());} function nmkr_save_sync_data($v){if(!empty($GLOBALS['fail_sync_data_save']))return false;return update_option('nmkr_sync_data',$v);}
function nmkr_with_sync_owner_lock($callback){return call_user_func($callback);} function nmkr_get_sync_owner(){return $GLOBALS['owner']??false;} function nmkr_sync_owner_matches($run,$state=null,$id=null){$o=nmkr_get_sync_owner();return is_array($o)&&($o['run_id']??'')===$run&&($state===null||($o['state']??'')===$state)&&($id===null||(int)($o['sync_stats_id']??0)===(int)$id);} function nmkr_release_sync_owner($run,$id=null,$state=null){if(!empty($GLOBALS['fail_owner_release']))return new Exception('synthetic owner lock failure');if(!nmkr_sync_owner_matches($run,$state,$id))return false;$GLOBALS['owner']=false;return true;}
function nmkr_sync_owner_transition_succeeded($v){return is_array($v)&&!empty($v['run_id']);} function nmkr_transition_sync_owner($run,$from,$to,$id=null){if(!empty($GLOBALS['fail_owner_transition']))return new WP_Error('lock','synthetic transition lock failure');if(!nmkr_sync_owner_matches($run,$from,$id))return false;$GLOBALS['owner']['state']=$to;return $GLOBALS['owner'];}
function nmkr_update_sync_heartbeat(){update_option('nmkr_sync_heartbeat',time());} function nmkr_cleanup_sync_heartbeat(){delete_option('nmkr_sync_heartbeat');} function nmkr_log_data_sync(){} function nmkr_log_ui_status(){} function nmkr_safe_getpid(){return 1;}
function nmkr_start_performance_tracking(){return array();} function nmkr_end_performance_tracking(){} function nmkr_sync_worker_checkpoint($run_id='',$sync_stats_id=0,$phase=''){if($phase==='after_token_detail_request'){$GLOBALS['detail_post_request_checkpoints']=($GLOBALS['detail_post_request_checkpoints']??0)+1;if(($GLOBALS['detail_request_mode']??'')==='checkpoint_failure')return new WP_Error('sync_checkpoint_persistence_failed','Synthetic checkpoint persistence failure.');}return true;} function nmkr_build_sync_api_execution_context(){return array();}
function nmkr_connect_fetch_projects(){$GLOBALS['project_http_dispatches']++;if(($GLOBALS['project_request_mode']??'')==='stop_wins')$GLOBALS['owner']['state']='stop_requested';return new WP_Error('nmkr_api_metric_evidence_persistence_failure','Synthetic project attempt-evidence persistence failure.');}
function nmkr_connect_fetch_nfts_by_project(){$GLOBALS['token_list_http_dispatches']++;return new WP_Error('nmkr_api_metric_evidence_persistence_failure','Synthetic token-list attempt-evidence persistence failure.');}
function nmkr_connect_fetch_nft_details(){
    $GLOBALS['token_detail_http_dispatches']++;
    if (($GLOBALS['detail_request_mode'] ?? '') === 'stop_wins') $GLOBALS['owner']['state'] = 'stop_requested';
    return new WP_Error('nmkr_api_metric_evidence_persistence_failure','Synthetic attempt-evidence persistence failure.');
}
function nmkr_get_sync_stats(){return array('total_duration'=>2,'average_time'=>.1,'request_count'=>3,'memory_used'=>4);} function nmkr_save_sync_metrics($m,$trusted=false){global $wpdb;$GLOBALS['metrics'][]=array_merge(array('id'=>count($GLOBALS['metrics'])+1),$m);$wpdb->insert_id=count($GLOBALS['metrics']);return $wpdb->insert_id;}
function nmkr_update_sync_stats($id,$data){if(!empty($GLOBALS['fail_history_update']))return false;if(empty($GLOBALS['leave_history_active']))$GLOBALS['history'][$id]=array_merge($GLOBALS['history'][$id],$data);$GLOBALS['history'][$id]['writes']++;return true;}
function nmkr_sync_finalization_checkpoint($point,$id){if(($GLOBALS['checkpoint']??'')==='interleaved_owner_release'&&$point==='after_finalization_lock'){$receipt=nmkr_get_sync_metrics_receipt($id);$GLOBALS['history'][$id]['status']='completed';$GLOBALS['history'][$id]['end_time']=$receipt['end_time'];$GLOBALS['options']['nmkr_sync_data']=array('status'=>'completed','completed'=>true,'sync_stats_id'=>$id,'run_id'=>$GLOBALS['owner']['run_id'],'end_time'=>$receipt['end_time']);$GLOBALS['owner']=false;throw new Exception('synthetic waiting finalizer');}if(($GLOBALS['checkpoint']??'')==='remove_owner_after_lock'&&$point==='after_finalization_lock'){$GLOBALS['owner']=false;return;}if(($GLOBALS['checkpoint']??'')==='replace_owner_after_lock'&&$point==='after_finalization_lock'){$GLOBALS['owner']=array('run_id'=>'99999999-9999-4999-8999-999999999999','mode'=>'direct','state'=>'finalizing','sync_stats_id'=>999);return;}if($GLOBALS['checkpoint']===$point)throw new Exception('synthetic crash at '.$point);}
class FakeWpdb { public $prefix='wp_',$options='wp_options',$insert_id=0,$fail_receipt=false,$snapshot=null,$locks=0;
 function prepare($q,...$args){foreach($args as $arg)$q=preg_replace('/%[sd]/',is_numeric($arg)?(string)$arg:"'".$arg."'",$q,1);return $q;}
 function get_col($q){return array('InnoDB','InnoDB');}
 function get_var($q){if(strpos($q,'GET_LOCK')!==false){$this->locks++;return 1;}if(strpos($q,'RELEASE_LOCK')!==false)return 1;if(preg_match("/option_name = '([^']+)'/",$q,$m)){if(!isset($GLOBALS['options'][$m[1]]))return null;return strpos($q,'option_id')!==false?1:serialize($GLOBALS['options'][$m[1]]);}return null;}
 function query($q){if($q==='START TRANSACTION')$this->snapshot=array($GLOBALS['metrics'],$GLOBALS['options']);if($q==='ROLLBACK'&&$this->snapshot)list($GLOBALS['metrics'],$GLOBALS['options'])=$this->snapshot;if($q==='COMMIT'||$q==='ROLLBACK')$this->snapshot=null;return true;}
 function insert($table,$data,$format=null){if($table===$this->options){if($this->fail_receipt){$this->fail_receipt=false;throw new Exception('post-metrics interruption');}$GLOBALS['options'][$data['option_name']]=unserialize($data['option_value']);return 1;}return 1;}
 function get_row($q){if(strpos($q,'nmkr_sync_metrics')!==false){$id=(int)preg_replace('/^.*id = (\d+).*$/','$1',$q);foreach($GLOBALS['metrics'] as $m)if((int)$m['id']===$id)return array('id'=>$id,'last_sync_time'=>$m['last_sync_time']);return null;}$id=(int)preg_replace('/^.*id = (\d+).*$/','$1',$q);return isset($GLOBALS['history'][$id])?$GLOBALS['history'][$id]:null;}
}
$wpdb=new FakeWpdb(); require dirname(__DIR__).'/includes/synchronization/nmkr-sync-progress-tracking.php';
$core_source=file_get_contents(dirname(__DIR__).'/includes/synchronization/nmkr-sync-core.php');
function load_core_helper($source, $name) {$start=strpos($source,'function '.$name.'(');$next_function=strpos($source,"\nfunction ",$start + 1);$next_comment=strpos($source,"\n/**",$start + 1);$ends=array_filter(array($next_function,$next_comment),function($value){return $value!==false;});$end=empty($ends)?strlen($source):min($ends);if($start===false){fwrite(STDERR,"FAIL: unable to load production helper {$name}\n");exit(1);}eval(substr($source,$start,$end-$start));}
load_core_helper($core_source,'nmkr_is_sync_worker_halt_error');
load_core_helper($core_source,'nmkr_is_fatal_api_error');
load_core_helper($core_source,'nmkr_handle_sync_worker_halt');
load_core_helper($core_source,'nmkr_handle_direct_worker_error');
load_core_helper($core_source,'nmkr_direct_sync_terminal_result');
load_core_helper($core_source,'nmkr_direct_sync_finalization_error');
load_core_helper($core_source,'nmkr_finalize_stop_winning_worker_failure');
load_core_helper($core_source,'nmkr_finalize_direct_worker_failure');
load_core_helper($core_source,'nmkr_finalize_pre_history_stop');
load_core_helper($core_source,'nmkr_finalize_pre_history_stop_on_early_failure');
load_core_helper($core_source,'nmkr_count_sync_steps');
load_core_helper($core_source,'nmkr_sync_projects');
load_core_helper($core_source,'nmkr_fetch_tokens_for_project');
load_core_helper($core_source,'nmkr_sync_token_details');
$ajax_source=file_get_contents(dirname(__DIR__).'/includes/synchronization/nmkr-sync-ajax-handlers.php');
load_core_helper($ajax_source,'nmkr_is_verified_failed_terminal_for_progress');
function check($ok,$m){if(!$ok){fwrite(STDERR,"FAIL: $m\n");exit(1);}echo "PASS: $m\n";}
function active_run($id=7){$GLOBALS['options']=array('nmkr_sync_data'=>array('status'=>'initializing','completed'=>false,'sync_stats_id'=>$id,'total_sync_duration'=>2,'memory_usage'=>4,'api_metric_evidence'=>array('request_count'=>3,'successful_requests'=>3,'failed_requests'=>0,'total_api_time'=>.3,'request_times'=>array(.1,.1,.1))),'nmkr_sync_in_progress'=>true,'nmkr_sync_near_completion'=>true,'nmkr_sync_heartbeat'=>123,'nmkr_sync_user_stopped'=>false);$GLOBALS['transients']=array('nmkr_sync_in_progress'=>true,'nmkr_current_sync_stats_live'=>array_merge($GLOBALS['final_metrics'],array('request_count'=>3,'successful_requests'=>3,'failed_requests'=>0,'request_times'=>array(.1,.1,.1))));$GLOBALS['hooks']=array_fill_keys(array('nmkr_execute_sync_background','nmkr_process_batch_hook','nmkr_sync_cron_hook','nmkr_install_sync_cron_hook'),1);$GLOBALS['history'][$id]=array('id'=>$id,'status'=>'initializing','end_time'=>null,'writes'=>0);}
function owned_run($id,$run){active_run($id);$GLOBALS['options']['nmkr_sync_data']['run_id']=$run;$GLOBALS['history'][$id]['run_id']=$run;$GLOBALS['owner']=array('run_id'=>$run,'mode'=>'direct','state'=>'finalizing','sync_stats_id'=>$id);}
$GLOBALS['final_metrics']=array('total_projects'=>1,'total_tokens'=>2,'total_sync_duration'=>2,'total_api_time'=>.3,'average_response_time'=>.1,'api_requests'=>3,'memory_usage'=>4);
$GLOBALS['owned_final']=array('metrics'=>$GLOBALS['final_metrics'],'items_processed'=>2,'items_successful'=>2,'items_failed'=>0,'items_skipped'=>0,'token_details_synced'=>2);
// Atomic interruption between metrics and receipt.
$wpdb->fail_receipt=true;check(nmkr_persist_sync_metrics_once(7,$GLOBALS['final_metrics'],'2026-01-02 03:04:05')===false&&count($GLOBALS['metrics'])===0,'post-metrics interruption rolls back both atomic writes');
// Sequential idempotency fixture: capture two active snapshots, then invoke complete finalizers one after another.
active_run();$contender_a_snapshot=nmkr_get_sync_data();$contender_b_snapshot=nmkr_get_sync_data();$a=nmkr_sync_data_complete(true,'',array('metrics'=>$GLOBALS['final_metrics']));$b=nmkr_sync_data_complete(true,'',array('metrics'=>$GLOBALS['final_metrics']));
check($contender_a_snapshot['status']==='initializing'&&$contender_b_snapshot['status']==='initializing'&&$a&&$b,'sequential finalizers begin from captured active snapshots and re-read canonical state');
check(count($GLOBALS['metrics'])===1&&$GLOBALS['history'][7]['writes']===1&&get_option('nmkr_sync_data')['status']==='completed','sequential complete finalizers create one metric, history transition, and terminal record');
$authoritative=get_option('nmkr_last_sync_time');check($authoritative===$GLOBALS['metrics'][0]['last_sync_time'],'sequential finalizers preserve one authoritative timestamp');
// Receipt-only resume after committed metrics with no live input.
active_run(8);$receipt=nmkr_persist_sync_metrics_once(8,$GLOBALS['final_metrics'],'2026-01-02 03:04:05');delete_transient('nmkr_current_sync_stats_live');$resumed=nmkr_sync_data_complete(true);
check($receipt&&$resumed&&count($GLOBALS['metrics'])===2&&$GLOBALS['history'][8]['writes']===1,'durable receipt resumes full finalization without live metrics or duplicate row');
// Missing referenced metric fails closed.
active_run(9);$GLOBALS['options']['nmkr_sync_finalizing_9']=array('sync_stats_id'=>9,'metrics_id'=>999,'end_time'=>'2026-01-02 03:04:05');delete_transient('nmkr_current_sync_stats_live');check(nmkr_sync_data_complete(true)===false&&get_option('nmkr_sync_data')['status']==='finalizing','receipt with missing metric fails closed and remains nonterminal');
// Missing, failed-update, and failed-readback history all block terminal exposure.
active_run(10);unset($GLOBALS['history'][10]);check(nmkr_sync_data_complete(true,'',array('metrics'=>$GLOBALS['final_metrics']))===false&&get_option('nmkr_sync_data')['status']!=='completed','missing owned history blocks completed terminal state');
active_run(11);$GLOBALS['fail_history_update']=true;check(nmkr_sync_data_complete(true,'',array('metrics'=>$GLOBALS['final_metrics']))===false&&get_option('nmkr_sync_data')['status']==='finalizing','failed history update blocks completed terminal state');unset($GLOBALS['fail_history_update']);
active_run(12);$GLOBALS['leave_history_active']=true;check(nmkr_sync_data_complete(true,'',array('metrics'=>$GLOBALS['final_metrics']))===false&&get_option('nmkr_sync_data')['status']==='finalizing','active history readback blocks completed terminal state');unset($GLOBALS['leave_history_active']);
// Conflicting terminal outcomes are immutable.
foreach(array('failed','error','stopped','aborted') as $status){active_run(20);$GLOBALS['history'][20]=array('id'=>20,'status'=>$status,'end_time'=>'2025-01-01 00:00:00','writes'=>0);check(nmkr_sync_data_complete(true,'',array('metrics'=>$GLOBALS['final_metrics']))===false&&$GLOBALS['history'][20]['status']===$status,'conflicting '.$status.' history is never relabeled completed');}
// Pre-receipt interruption stays active/finalizing.
active_run(30);$wpdb->fail_receipt=true;check(nmkr_sync_data_complete(true,'',array('metrics'=>$GLOBALS['final_metrics']))===false&&get_option('nmkr_sync_in_progress')===true&&get_option('nmkr_sync_data')['status']==='finalizing','pre-commit interruption remains detectable and recoverable');
// Post-receipt cleanup interruption preserves success evidence and resumes without live metrics.
active_run(31);$GLOBALS['checkpoint']='before_terminal_record';check(nmkr_sync_data_complete(true,'',array('metrics'=>$GLOBALS['final_metrics']))===false&&nmkr_sync_has_committed_success(31)&&$GLOBALS['history'][31]['status']==='completed'&&wp_next_scheduled('nmkr_resume_sync_finalization',array(31)),'post-receipt cleanup error preserves committed success instead of failure');$GLOBALS['checkpoint']='';delete_transient('nmkr_current_sync_stats_live');check(nmkr_sync_data_complete(true)&&get_option('nmkr_sync_data')['status']==='completed','post-receipt interruption resumes without live metrics');
// Terminal is written only after cleanup; even an immediate post-write crash leaves no leftovers.
active_run(32);$GLOBALS['checkpoint']='after_terminal_record';check(nmkr_sync_data_complete(true,'',array('metrics'=>$GLOBALS['final_metrics']))===false&&get_option('nmkr_sync_data')['status']==='completed'&&nmkr_sync_finalization_resume_pending(32)&&get_transient('nmkr_current_sync_stats_live')===false&&!nmkr_is_sync_canonically_finished(get_option('nmkr_sync_data'),false,false,false,false,true),'post-terminal crash retains resume evidence and remains nonterminal');$metrics_before=count($GLOBALS['metrics']);$GLOBALS['checkpoint']='';unset($GLOBALS['hooks'][hook_key('nmkr_resume_sync_finalization',array(32))]);check(nmkr_resume_sync_finalization(32)&&!nmkr_sync_finalization_resume_pending(32)&&count($GLOBALS['metrics'])===$metrics_before&&$GLOBALS['history'][32]['writes']===1,'post-terminal callback clears only resume state without metrics or history rewrite');
$terminal=array('status'=>'completed','completed'=>true,'sync_stats_id'=>7);check(!nmkr_is_sync_canonically_finished($terminal,false,false,true,false),'durable abort marker prevents finished');check(!nmkr_is_sync_canonically_finished($terminal,false,false,false,true),'transient abort marker prevents finished');check(!nmkr_is_sync_canonically_finished($terminal,true,false,false,false)&&!nmkr_is_sync_canonically_finished($terminal,false,true,false,false),'either in-progress marker prevents finished');check(nmkr_is_sync_canonically_finished($terminal,false,false,false,false),'only canonical state with all markers inactive is finished');
foreach(array('success','completed','failed','error','stopped','cancelled','aborted') as $status){$GLOBALS['history'][40]=array('id'=>40,'status'=>$status,'end_time'=>'2026-01-02 03:04:05','writes'=>0);$GLOBALS['options']['nmkr_sync_data']=array('status'=>$status,'completed'=>true,'sync_stats_id'=>40,'end_time'=>'2026-01-02 03:04:05');nmkr_sync_data_complete(false,'again');check($GLOBALS['history'][40]['writes']===0&&$GLOBALS['history'][40]['status']===$status,'existing '.$status.' terminal row remains immutable');}

// Dedicated durable resume scheduling never repeats business work.
active_run(50);$GLOBALS['checkpoint']='receipt_committed';$before_metrics=count($GLOBALS['metrics']);check(nmkr_sync_data_complete(true,'',array('metrics'=>$GLOBALS['final_metrics']))===false&&wp_next_scheduled('nmkr_resume_sync_finalization',array(50)),'sync_finalization_pending window has an exact run-owned resume event');$GLOBALS['checkpoint']='';unset($GLOBALS['hooks'][hook_key('nmkr_resume_sync_finalization',array(50))]);check(nmkr_resume_sync_finalization(50)&&count($GLOBALS['metrics'])===$before_metrics+1&&$GLOBALS['history'][50]['writes']===1,'resume invokes only terminalization and does not duplicate metrics or history');
active_run(51);$wpdb->fail_receipt=true;check(nmkr_sync_data_complete(true,'',array('metrics'=>$GLOBALS['final_metrics']))===false&&is_array(get_option(nmkr_sync_finalization_resume_key(51),false)),'pre-receipt interruption retains minimal durable resume input');delete_transient('nmkr_current_sync_stats_live');unset($GLOBALS['hooks'][hook_key('nmkr_resume_sync_finalization',array(51))]);check(nmkr_resume_sync_finalization(51)&&$GLOBALS['history'][51]['writes']===1,'pre-receipt resume completes without business synchronization or live transient');
active_run(52);nmkr_save_sync_finalization_resume(52,array('metrics'=>$GLOBALS['final_metrics']));check(nmkr_schedule_sync_finalization_resume(52,0)&&nmkr_schedule_sync_finalization_resume(52,0)&&count(array_filter(array_keys($GLOBALS['hooks']),function($k){return $k==='nmkr_resume_sync_finalization:52';}))===1,'duplicate resume scheduling is prevented');
$GLOBALS['scheduled_delays']=array();foreach(array(0,1,2,3,4) as $attempt){unset($GLOBALS['hooks'][hook_key('nmkr_resume_sync_finalization',array(60))]);nmkr_schedule_sync_finalization_resume(60,$attempt);}check($GLOBALS['scheduled_delays']===array(3,6,12,24,30),'resume backoff is exponential and capped at 30 seconds');
active_run(53);$GLOBALS['options'][nmkr_sync_finalization_resume_key(53)]=array('sync_stats_id'=>53,'attempt'=>4);$GLOBALS['options']['nmkr_sync_finalizing_53']=array('sync_stats_id'=>53,'metrics_id'=>999,'end_time'=>'2026-01-02 03:04:05');check(nmkr_resume_sync_finalization(53)===false&&get_option('nmkr_sync_status')==='finalization_error'&&get_option('nmkr_sync_in_progress')===true&&get_option('nmkr_sync_data')['status']!=='completed','retry exhaustion preserves pending nonterminal operator-visible state');
active_run(55);nmkr_save_sync_finalization_resume(55,array('metrics'=>$GLOBALS['final_metrics']));$GLOBALS['options']['nmkr_sync_data']['status']='finalizing';check(nmkr_maintain_sync_finalization_resume($GLOBALS['options']['nmkr_sync_data'])&&wp_next_scheduled('nmkr_resume_sync_finalization',array(55)),'stale finalizing maintenance schedules resume without performing finalization');
nmkr_clear_sync_finalization_resume(55);check(!wp_next_scheduled('nmkr_resume_sync_finalization',array(55))&&get_option(nmkr_sync_finalization_resume_key(55),false)===false,'Stop and immutable cleanup can neutralize exact resume state');
// Cleanup readback failure retains resume state and prevents terminal exposure.
active_run(54);$GLOBALS['fail_cleanup']='transient:nmkr_current_sync_stats_live';check(nmkr_sync_data_complete(true,'',array('metrics'=>$GLOBALS['final_metrics']))===false&&get_option('nmkr_sync_data')['status']==='finalizing'&&wp_next_scheduled('nmkr_resume_sync_finalization',array(54)),'cleanup readback disagreement retains resume and blocks terminal exposure');unset($GLOBALS['fail_cleanup']);
foreach(array('option:nmkr_sync_in_progress','option:nmkr_sync_near_completion','option:nmkr_sync_heartbeat','option:nmkr_sync_worker_lock','transient:nmkr_sync_in_progress','transient:nmkr_current_sync_stats_live','transient:nmkr_active_sync_metrics','transient:nmkr_sync_performance_metrics') as $index=>$failure){$id=70+$index;active_run($id);$GLOBALS['options']['nmkr_sync_worker_lock']=1;$GLOBALS['transients']['nmkr_active_sync_metrics']=1;$GLOBALS['transients']['nmkr_sync_performance_metrics']=1;$GLOBALS['fail_cleanup']=$failure;check(nmkr_sync_data_complete(true,'',array('metrics'=>$GLOBALS['final_metrics']))===false&&get_option('nmkr_sync_data')['status']==='finalizing','cleanup failure '.$failure.' blocks completed exposure');unset($GLOBALS['fail_cleanup']);}

// Post-terminal resume cleanup failure preserves terminal authority and retry evidence.
active_run(90);$GLOBALS['fail_cleanup']='hook:nmkr_resume_sync_finalization';$metrics_before=count($GLOBALS['metrics']);check(nmkr_sync_data_complete(true,'',array('metrics'=>$GLOBALS['final_metrics']))===false&&get_option('nmkr_sync_data')['status']==='completed'&&nmkr_sync_finalization_resume_pending(90)&&!nmkr_is_sync_canonically_finished(get_option('nmkr_sync_data'),false,false,false,false,true),'post-terminal resume cleanup failure preserves terminal record and finished false');check(count($GLOBALS['metrics'])===$metrics_before+1&&$GLOBALS['history'][90]['writes']===1,'post-terminal cleanup failure does not rewrite committed work');unset($GLOBALS['fail_cleanup']);
// Completed metrics reject missing/inconsistent evidence while accepting measured zero.
active_run(87);delete_transient('nmkr_current_sync_stats_live');unset($GLOBALS['options']['nmkr_sync_data']['api_metric_evidence']);$missing=nmkr_build_final_sync_metrics($GLOBALS['final_metrics'],$GLOBALS['options']['nmkr_sync_data']);check(is_wp_error($missing)&&$missing->get_error_code()==='nmkr_final_metrics_unavailable','missing live and durable samples fail closed');
active_run(88);$GLOBALS['transients']['nmkr_current_sync_stats_live']['request_times']=array(.1);$inconsistent=nmkr_build_final_sync_metrics($GLOBALS['final_metrics'],$GLOBALS['options']['nmkr_sync_data']);check(is_wp_error($inconsistent)&&$inconsistent->get_error_code()==='nmkr_final_metrics_inconsistent','inconsistent sample count fails closed');
active_run(89);$zero_evidence=array('request_count'=>1,'successful_requests'=>1,'failed_requests'=>0,'total_api_time'=>0.0,'request_times'=>array(0.0));$GLOBALS['transients']['nmkr_current_sync_stats_live']=array_merge($GLOBALS['transients']['nmkr_current_sync_stats_live'],$zero_evidence);$zero=nmkr_build_final_sync_metrics($GLOBALS['final_metrics'],$GLOBALS['options']['nmkr_sync_data']);check(is_array($zero)&&$zero['total_api_time']===0.0&&$zero['average_response_time']===0.0,'measured zero sample is valid completed evidence');
// Shared builder reconstructs complete direct/batch snapshots without the live transient.
active_run(91);$GLOBALS['options']['nmkr_sync_data']['total_projects']=2;$GLOBALS['options']['nmkr_sync_data']['total_tokens']=3;delete_transient('nmkr_current_sync_stats_live');$built=nmkr_build_final_sync_metrics(false,$GLOBALS['options']['nmkr_sync_data']);check(count(array_intersect_key($built,array_flip(array('total_projects','total_tokens','total_sync_duration','total_api_time','average_response_time','api_requests','memory_usage'))))===7&&nmkr_sync_data_complete(true,'',array('metrics'=>$built)),'direct-owned totals reconstruct complete metrics without transient');
active_run(92);delete_transient('nmkr_current_sync_stats_live');$batch_built=nmkr_build_final_sync_metrics(array('total_sync_duration'=>4),$GLOBALS['options']['nmkr_sync_data'],array('total_projects'=>4,'total_tokens'=>5));check($batch_built['total_projects']===4&&$batch_built['total_tokens']===5&&nmkr_sync_data_complete(true,'',array('metrics'=>$batch_built)),'batch-owned totals provide complete metrics without transient');
// Resume persistence and scheduling must verify durable protection before finalization.
active_run(93);$GLOBALS['fail_cleanup']='option:'.nmkr_sync_finalization_resume_key(93);check(nmkr_sync_data_complete(true,'',array('metrics'=>$GLOBALS['final_metrics']))===false&&get_option('nmkr_sync_data')['status']==='finalizing'&&count($GLOBALS['metrics'])===$metrics_before+3,'resume option readback failure blocks interruption-prone persistence');unset($GLOBALS['fail_cleanup']);
active_run(94);$GLOBALS['fail_schedule']=true;check(nmkr_sync_data_complete(true,'',array('metrics'=>$GLOBALS['final_metrics']))===false&&get_option('nmkr_sync_data')['status']==='finalizing'&&get_option('nmkr_sync_status')==='finalization_error','resume scheduling failure remains operator-visible and nonterminal');unset($GLOBALS['fail_schedule']);
$phase16=file_get_contents(dirname(__DIR__).'/scripts/nmkr-real-sync-phase16a-state.php');check(strpos($phase16,"'finalization_resume_marker_count'")!==false&&strpos($phase16,"'nmkr_resume_sync_finalization'")!==false,'Phase 16A aggregates leftover resume option and event evidence');

// Focused Start guard cases use the production predicate and exact-run evidence.
$GLOBALS['options']=array('nmkr_sync_data'=>array('status'=>'finalizing','sync_stats_id'=>101));$GLOBALS['hooks']=array();check(nmkr_sync_start_blocked_by_finalization(get_option('nmkr_sync_data')),'Start rejects finalizing current run');
$GLOBALS['options']=array('nmkr_sync_data'=>array('status'=>'completed','sync_stats_id'=>102),'nmkr_sync_finalization_resume_102'=>array('sync_stats_id'=>102));check(nmkr_sync_start_blocked_by_finalization(get_option('nmkr_sync_data')),'Start rejects completed current run with exact resume option');
$GLOBALS['options']=array('nmkr_sync_data'=>array('status'=>'completed','sync_stats_id'=>103));$GLOBALS['hooks']=array(hook_key('nmkr_resume_sync_finalization',array(103))=>time()+3);check(nmkr_sync_start_blocked_by_finalization(get_option('nmkr_sync_data')),'Start rejects completed current run with exact resume event');
$GLOBALS['options']=array('nmkr_sync_data'=>array('status'=>'finalization_error','sync_stats_id'=>104),'nmkr_sync_finalization_resume_104'=>array('sync_stats_id'=>104));check(nmkr_sync_start_blocked_by_finalization(get_option('nmkr_sync_data')),'Start rejects finalization_error with exact resume evidence');
$GLOBALS['options']=array('nmkr_sync_data'=>array('status'=>'completed','sync_stats_id'=>105),'nmkr_sync_finalization_resume_999'=>array('sync_stats_id'=>999));$GLOBALS['hooks']=array();check(!nmkr_sync_start_blocked_by_finalization(get_option('nmkr_sync_data')),'clean completed current run ignores unrelated historical resume evidence');
check(!nmkr_sync_start_blocked_by_finalization(array('status'=>'completed','sync_stats_id'=>'bad')),'malformed run ID never invokes exact-run pending check');
// Dashboard canonical observer cases; snapshots prove classification performs no writes.
$GLOBALS['options']=array('nmkr_sync_data'=>array('status'=>'finalizing','completed'=>false,'sync_stats_id'=>110),'nmkr_sync_in_progress'=>true);$GLOBALS['transients']=array('nmkr_sync_progress'=>100);$GLOBALS['hooks']=array();$before=array($GLOBALS['options'],$GLOBALS['transients'],$GLOBALS['hooks']);$state=nmkr_get_canonical_dashboard_sync_state();check($state['running']&&!$state['finished']&&$before===array($GLOBALS['options'],$GLOBALS['transients'],$GLOBALS['hooks']),'progress 100 finalizing remains active and observer performs no writes');
$GLOBALS['options']=array('nmkr_sync_data'=>array('status'=>'completed','completed'=>true,'sync_stats_id'=>111),'nmkr_sync_finalization_resume_111'=>array('sync_stats_id'=>111));$GLOBALS['transients']=array('nmkr_sync_progress'=>100);$GLOBALS['hooks']=array();$state=nmkr_get_canonical_dashboard_sync_state();check($state['running']&&$state['finalization_pending']&&!$state['finished'],'completed terminal with resume option remains pending');
unset($GLOBALS['options']['nmkr_sync_finalization_resume_111']);$GLOBALS['hooks']=array(hook_key('nmkr_resume_sync_finalization',array(111))=>time()+3);$state=nmkr_get_canonical_dashboard_sync_state();check($state['running']&&$state['finalization_pending']&&!$state['finished'],'completed terminal with resume event remains pending');
$GLOBALS['hooks']=array();$state=nmkr_get_canonical_dashboard_sync_state();check(!$state['running']&&$state['finished'],'completed terminal without resume evidence reports finished');
$GLOBALS['options']=array('nmkr_sync_data'=>array('status'=>'processing','completed'=>false,'sync_stats_id'=>112),'nmkr_sync_in_progress'=>true,'nmkr_sync_error'=>'recoverable');$GLOBALS['transients']=array('nmkr_sync_progress'=>100);$state=nmkr_get_canonical_dashboard_sync_state();check($state['running']&&get_option('nmkr_sync_in_progress')===true,'recoverable error and raw 100 do not clear active state');
$dashboard_ui=file_get_contents(dirname(__DIR__).'/includes/pages/dashboard/nmkr-dashboard-ui.php');check(strpos($dashboard_ui,'if (response.data.sync_in_progress)')!==false&&strpos($dashboard_ui,'window.NMKRProgress.startPolling();')!==false,'dashboard reload resumes the existing polling loop for pending state');
$start_source=file_get_contents(dirname(__DIR__).'/includes/synchronization/nmkr-sync-ajax-handlers.php');$start_body=substr($start_source,strpos($start_source,'function nmkr_start_sync_handler()'),strpos($start_source,'function nmkr_cleanup_sync_jobs_handler()')-strpos($start_source,'function nmkr_start_sync_handler()'));check(strpos($start_body,"check_ajax_referer('nmkr_sync_nonce', 'nonce')")<strpos($start_body,"current_user_can( 'nmkr_manage_sync' )")&&strpos($start_body,"current_user_can( 'nmkr_manage_sync' )")<strpos($start_body,'nmkr_admit_sync_owner')&&strpos($start_body,'nmkr_admit_sync_owner')<strpos($start_body,"delete_option('nmkr_sync_user_stopped')")&&strpos($start_body,"delete_option('nmkr_sync_user_stopped')")<strpos($start_body,"delete_option('nmkr_sync_last_result')"),'Start clears the durable legacy abort marker only after guarded admission');
$dashboard_source=file_get_contents(dirname(__DIR__).'/includes/pages/dashboard/nmkr-dashboard-ajax.php');$status_body=substr($dashboard_source,strpos($dashboard_source,'function nmkr_check_api_status()'),strpos($dashboard_source,'function nmkr_get_sync_statistics_ajax()')-strpos($dashboard_source,'function nmkr_check_api_status()'));check(strpos($status_body,"update_option('nmkr_sync_in_progress'")===false&&strpos($status_body,"delete_option('nmkr_sync_in_progress'")===false&&strpos($status_body,"delete_transient('nmkr_sync_in_progress'")===false,'dashboard API status handler performs no synchronization lifecycle writes');
$background=file_get_contents(dirname(__DIR__).'/includes/synchronization/nmkr-sync-ajax-handlers.php');$tracking=file_get_contents(dirname(__DIR__).'/includes/synchronization/nmkr-sync-progress-tracking.php');check(strpos($background,"get_error_code() === 'sync_finalization_pending'")!==false&&strpos($tracking,"add_action('nmkr_resume_sync_finalization'")!==false,'background pending handling is backed by registered durable resume scheduling');
$ajax=file_get_contents(dirname(__DIR__).'/includes/synchronization/nmkr-sync-ajax-handlers.php');$js=file_get_contents(dirname(__DIR__).'/js/nmkr-sync-progress.js');check(strpos($ajax,'nmkr_is_sync_canonically_finished(')!==false&&strpos($ajax,"if (\$progress_int === 100) {\n        delete_transient('nmkr_current_sync_stats_live')")===false,'polling stays read-only and uses canonical predicate');check(strpos($js,'if (finished === true)')!==false&&strpos($js,'finished === true || validProgress === 100')===false,'frontend never finishes from raw 100 percent progress');

// Progress polling exposes only verified ownerless failed terminals and does
// not mutate terminal history while classifying them.
$progress_failed_id=119;$progress_failed_run='abababab-1111-4111-8111-111111111111';$GLOBALS['history'][$progress_failed_id]=array('id'=>$progress_failed_id,'run_id'=>$progress_failed_run,'status'=>'failed','end_time'=>'2026-01-02 03:04:05','writes'=>0);$progress_failed=array('status'=>'failed','completed'=>true,'run_id'=>$progress_failed_run,'sync_stats_id'=>$progress_failed_id,'end_time'=>'2026-01-02 03:04:05');$GLOBALS['owner']=false;$GLOBALS['hooks']=array();$before=array($GLOBALS['options'],$GLOBALS['transients'],$GLOBALS['history'],$GLOBALS['owner']);check(nmkr_is_verified_failed_terminal_for_progress($progress_failed,false,false)&&$before===array($GLOBALS['options'],$GLOBALS['transients'],$GLOBALS['history'],$GLOBALS['owner']),'verified ownerless failed terminal bypass predicate is exact and read-only');
$verification_before=array($GLOBALS['options'],$GLOBALS['transients'],$GLOBALS['history'],$GLOBALS['owner']);check(nmkr_verify_sync_terminal_result($progress_failed,'failed')&&$verification_before===array($GLOBALS['options'],$GLOBALS['transients'],$GLOBALS['history'],$GLOBALS['owner']),'matching direct history run ID verifies terminal read-only');
$GLOBALS['history'][$progress_failed_id]['run_id']='bbbbbbbb-1111-4111-8111-111111111111';check(!nmkr_verify_sync_terminal_result($progress_failed,'failed')&&!nmkr_is_verified_failed_terminal_for_progress($progress_failed,false,false),'mismatched direct history run ID rejects failed terminal authority');
$GLOBALS['history'][$progress_failed_id]['run_id']='';check(!nmkr_verify_sync_terminal_result($progress_failed,'failed'),'missing direct history run ID rejects terminal verification');
$GLOBALS['history'][$progress_failed_id]['run_id']='not-a-run';check(!nmkr_verify_sync_terminal_result($progress_failed,'failed'),'malformed direct history run ID rejects terminal verification');
$GLOBALS['history'][$progress_failed_id]['run_id']=$progress_failed_run;
$GLOBALS['options'][nmkr_sync_finalization_resume_key($progress_failed_id)]=array('pending'=>true);check(!nmkr_is_verified_failed_terminal_for_progress($progress_failed,false,true),'failed terminal with resume evidence remains nonterminal');unset($GLOBALS['options'][nmkr_sync_finalization_resume_key($progress_failed_id)]);
$successor=array('run_id'=>'abababab-2222-4222-8222-222222222222','mode'=>'direct','state'=>'running','sync_stats_id'=>148);$GLOBALS['owner']=$successor;check(!nmkr_is_verified_failed_terminal_for_progress($progress_failed,true,false)&&$GLOBALS['owner']===$successor,'active successor is never terminated by predecessor failed/error evidence');$GLOBALS['owner']=false;
$legacy_failed=array('status'=>'failed','completed'=>true,'run_id'=>'not-a-run','sync_stats_id'=>0,'end_time'=>'2026-01-02 03:04:05');check(!nmkr_is_verified_failed_terminal_for_progress($legacy_failed,false,false),'malformed legacy error state remains eligible for generic critical-error handling');
$progress_body=substr($ajax,strpos($ajax,'function nmkr_sync_progress_handler()'),strpos($ajax,'function nmkr_stop_sync_handler()')-strpos($ajax,'function nmkr_sync_progress_handler()'));check(strpos($progress_body,"check_ajax_referer('nmkr_sync_nonce', 'nonce')")<strpos($progress_body,"current_user_can( 'nmkr_view_dashboard' )")&&strpos($progress_body,'nmkr_is_verified_failed_terminal_for_progress(')!==false,'progress failed-terminal classification remains nonce/capability protected');

// Owner release is part of terminalization and remains durably resumable.
$owned_id=120;$owned_run='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';owned_run($owned_id,$owned_run);$prepared=nmkr_prepare_sync_finalization($owned_id,array_merge($GLOBALS['owned_final'],array('run_id'=>$owned_run)),nmkr_get_sync_data());$GLOBALS['fail_owner_release']=true;$before_metrics=count($GLOBALS['metrics']);check(nmkr_sync_data_complete(true,'',$prepared,false,true)===false&&is_array(nmkr_get_sync_owner())&&nmkr_sync_finalization_resume_pending($owned_id),'owner-release lock failure retains exact owner and retry evidence');unset($GLOBALS['fail_owner_release']);$writes=$GLOBALS['history'][$owned_id]['writes'];check(is_array(nmkr_sync_data_complete(true,'',$prepared,true,true))&&nmkr_get_sync_owner()===false&&count($GLOBALS['metrics'])===$before_metrics+1&&$GLOBALS['history'][$owned_id]['writes']===$writes,'later terminal retry releases owner without duplicate metrics or history writes');check(is_array(nmkr_sync_data_complete(true,'',$prepared,true,true))&&!nmkr_sync_finalization_resume_pending($owned_id),'waiting finalizer accepts verified terminal result with absent owner without resume resurrection');$GLOBALS['owner']=array('run_id'=>'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','mode'=>'direct','state'=>'queued','sync_stats_id'=>0);check(nmkr_sync_data_complete(true,'',$prepared,true,true)===false&&$GLOBALS['owner']['run_id']==='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','mismatched successor is not treated as released owner');$GLOBALS['owner']=false;
$interleave_id=121;$interleave_run='cccccccc-cccc-4ccc-8ccc-cccccccccccc';owned_run($interleave_id,$interleave_run);$record=nmkr_save_sync_finalization_resume($interleave_id,array_merge($GLOBALS['owned_final'],array('run_id'=>$interleave_run)));nmkr_schedule_sync_finalization_resume($interleave_id);nmkr_persist_sync_metrics_once($interleave_id,$GLOBALS['final_metrics'],'2026-01-02 03:04:05');$GLOBALS['checkpoint']='interleaved_owner_release';check(nmkr_resume_sync_finalization($interleave_id)===true&&nmkr_get_sync_owner()===false&&!nmkr_sync_finalization_resume_pending($interleave_id),'waiting resume observes concurrent completion and never resurrects retry evidence');$GLOBALS['checkpoint']='';
$cleanup_id=122;$cleanup_run='dddddddd-dddd-4ddd-8ddd-dddddddddddd';owned_run($cleanup_id,$cleanup_run);$prepared=nmkr_prepare_sync_finalization($cleanup_id,array_merge($GLOBALS['owned_final'],array('run_id'=>$cleanup_run)),nmkr_get_sync_data());nmkr_sync_data_complete(true,'',$prepared,false,true);$metrics_count=count($GLOBALS['metrics']);$writes=$GLOBALS['history'][$cleanup_id]['writes'];update_option(nmkr_sync_finalization_resume_key($cleanup_id),$prepared,false);nmkr_schedule_sync_finalization_resume($cleanup_id);$GLOBALS['fail_cleanup']='option:'.nmkr_sync_finalization_resume_key($cleanup_id);check(nmkr_sync_data_complete(true,'',$prepared,true,true)===false&&nmkr_sync_finalization_resume_pending($cleanup_id),'ownerless terminal option-cleanup failure remains pending');$GLOBALS['fail_cleanup']='hook:nmkr_resume_sync_finalization';check(nmkr_sync_data_complete(true,'',$prepared,true,true)===false&&nmkr_sync_finalization_resume_pending($cleanup_id),'ownerless terminal event-cleanup failure remains pending');unset($GLOBALS['fail_cleanup']);check(is_array(nmkr_sync_data_complete(true,'',$prepared,true,true))&&count($GLOBALS['metrics'])===$metrics_count&&$GLOBALS['history'][$cleanup_id]['writes']===$writes,'later ownerless cleanup retry does not rewrite terminal work');
$handoff_id=123;$handoff_run='eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee';active_run($handoff_id);$GLOBALS['options']['nmkr_sync_data']['run_id']=$handoff_run;$GLOBALS['owner']=array('run_id'=>$handoff_run,'mode'=>'direct','state'=>'running','sync_stats_id'=>$handoff_id);$record=nmkr_prepare_sync_finalization($handoff_id,array_merge($GLOBALS['owned_final'],array('run_id'=>$handoff_run)),nmkr_get_sync_data());unset($GLOBALS['hooks'][hook_key('nmkr_resume_sync_finalization',array($handoff_id))]);$GLOBALS['fail_owner_transition']=true;check(nmkr_resume_sync_finalization($handoff_id)===false&&is_array(get_option(nmkr_sync_finalization_resume_key($handoff_id),false))&&wp_next_scheduled('nmkr_resume_sync_finalization',array($handoff_id)),'handoff transition WP_Error preserves exact durable retry without business replay');unset($GLOBALS['fail_owner_transition']);check(nmkr_resume_sync_finalization($handoff_id)===true&&nmkr_get_sync_owner()===false&&get_option('nmkr_sync_data')['status']==='completed','resume claims running handoff and terminalizes exactly once');
$stop_handoff_id=133;$stop_handoff_run='13333333-3333-4333-8333-333333333333';active_run($stop_handoff_id);$GLOBALS['options']['nmkr_sync_data']['run_id']=$stop_handoff_run;$GLOBALS['owner']=array('run_id'=>$stop_handoff_run,'mode'=>'direct','state'=>'running','sync_stats_id'=>$stop_handoff_id);$record=nmkr_prepare_sync_finalization($stop_handoff_id,array_merge($GLOBALS['owned_final'],array('run_id'=>$stop_handoff_run)),nmkr_get_sync_data());$GLOBALS['owner']['state']='stop_requested';$metrics_before=count($GLOBALS['metrics']);check(nmkr_resume_sync_finalization($stop_handoff_id)===true&&nmkr_get_sync_owner()===false&&get_option('nmkr_sync_data')['status']==='stopped'&&$GLOBALS['history'][$stop_handoff_id]['status']==='stopped'&&count($GLOBALS['metrics'])===$metrics_before,'Stop winning the completion handoff terminalizes stopped without metrics or a stranded owner');
$mismatch_id=124;$mismatch_run='ffffffff-ffff-4fff-8fff-ffffffffffff';active_run($mismatch_id);$GLOBALS['options']['nmkr_sync_data']['run_id']=$mismatch_run;$record=nmkr_save_sync_finalization_resume($mismatch_id,array_merge($GLOBALS['owned_final'],array('run_id'=>$mismatch_run)));nmkr_schedule_sync_finalization_resume($mismatch_id);$GLOBALS['owner']=array('run_id'=>$handoff_run,'mode'=>'direct','state'=>'running','sync_stats_id'=>999);$before_owner=$GLOBALS['owner'];check(nmkr_resume_sync_finalization($mismatch_id)===false&&$GLOBALS['owner']===$before_owner,'mismatched owner cannot claim durable finalization handoff');

$evidence_id=125;$evidence_run='abababab-abab-4bab-8bab-abababababab';active_run($evidence_id);$GLOBALS['options']['nmkr_sync_data']['run_id']=$evidence_run;$GLOBALS['owner']=array('run_id'=>$evidence_run,'mode'=>'direct','state'=>'running','sync_stats_id'=>$evidence_id);$record=nmkr_save_sync_finalization_resume($evidence_id,array_merge($GLOBALS['owned_final'],array('run_id'=>$evidence_run)));check(!nmkr_sync_finalization_handoff_pending($evidence_run,$evidence_id),'resume option without exact event is not executable handoff');$GLOBALS['fail_schedule']=true;check(nmkr_preserve_and_schedule_sync_finalization_retry($record,false)===false&&!nmkr_sync_finalization_resume_event_scheduled($evidence_id)&&get_option('nmkr_sync_status')==='finalization_error','retry scheduling failure exposes non-executable finalization error');unset($GLOBALS['fail_schedule']);check(nmkr_preserve_and_schedule_sync_finalization_retry($record,false)===true&&nmkr_sync_finalization_resume_event_scheduled($evidence_id),'verified retry scheduling creates exact event');wp_clear_scheduled_hook('nmkr_resume_sync_finalization',array($evidence_id));$record['attempt']=4;check(nmkr_preserve_and_schedule_sync_finalization_retry($record,true)===false&&(int)get_option(nmkr_sync_finalization_resume_key($evidence_id))['attempt']===5&&!nmkr_sync_finalization_resume_event_scheduled($evidence_id)&&get_option('nmkr_sync_status')==='finalization_error','attempt five is retained without scheduling sixth attempt');$record['attempt']=0;update_option(nmkr_sync_finalization_resume_key($evidence_id),$record,false);$GLOBALS['fail_cleanup']='option:'.nmkr_sync_finalization_resume_key($evidence_id);check(nmkr_preserve_and_schedule_sync_finalization_retry($record,true)===false,'retry option write-readback failure is detected');unset($GLOBALS['fail_cleanup']);
$guard_id=126;$guard_run='cdcdcdcd-cdcd-4dcd-8dcd-cdcdcdcdcdcd';owned_run($guard_id,$guard_run);$prepared=nmkr_prepare_sync_finalization($guard_id,array_merge($GLOBALS['owned_final'],array('run_id'=>$guard_run)),nmkr_get_sync_data());$GLOBALS['owner']=false;$before=array(count($GLOBALS['metrics']),$GLOBALS['history'][$guard_id],$GLOBALS['options']['nmkr_sync_data'],$GLOBALS['transients']);check(nmkr_sync_data_complete(true,'',$prepared,true,true)===false&&$before===array(count($GLOBALS['metrics']),$GLOBALS['history'][$guard_id],$GLOBALS['options']['nmkr_sync_data'],$GLOBALS['transients']),'ownerless nonterminal finalizer performs no lifecycle mutation');
owned_run(127,'dededede-dede-4ded-8ded-dededededede');$prepared=nmkr_prepare_sync_finalization(127,array_merge($GLOBALS['owned_final'],array('run_id'=>'dededede-dede-4ded-8ded-dededededede')),nmkr_get_sync_data());$before=array(count($GLOBALS['metrics']),$GLOBALS['history'][127]['writes']);$GLOBALS['checkpoint']='remove_owner_after_lock';check(nmkr_sync_data_complete(true,'',$prepared,true,true)===false&&$before===array(count($GLOBALS['metrics']),$GLOBALS['history'][127]['writes']),'owner removal after finalization lock blocks nonterminal mutations');$GLOBALS['checkpoint']='';
owned_run(128,'efefefef-efef-4fef-8fef-efefefefefef');$prepared=nmkr_prepare_sync_finalization(128,array_merge($GLOBALS['owned_final'],array('run_id'=>'efefefef-efef-4fef-8fef-efefefefefef')),nmkr_get_sync_data());$before=array(count($GLOBALS['metrics']),$GLOBALS['history'][128]['writes']);$GLOBALS['checkpoint']='replace_owner_after_lock';check(nmkr_sync_data_complete(true,'',$prepared,true,true)===false&&$GLOBALS['owner']['sync_stats_id']===999&&$before===array(count($GLOBALS['metrics']),$GLOBALS['history'][128]['writes']),'successor replacement after lock blocks mutation and preserves successor');$GLOBALS['checkpoint']='';
$initial_fail_id=129;$initial_fail_run='12121212-1212-4212-8212-121212121212';active_run($initial_fail_id);$GLOBALS['options']['nmkr_sync_data']['run_id']=$initial_fail_run;$GLOBALS['owner']=array('run_id'=>$initial_fail_run,'mode'=>'direct','state'=>'running','sync_stats_id'=>$initial_fail_id);$GLOBALS['fail_schedule']=true;$initial_prepared=nmkr_prepare_sync_finalization($initial_fail_id,array_merge($GLOBALS['owned_final'],array('run_id'=>$initial_fail_run)),nmkr_get_sync_data());unset($GLOBALS['fail_schedule']);$saved=get_option(nmkr_sync_finalization_resume_key($initial_fail_id),false);check($initial_prepared===false&&nmkr_is_valid_sync_finalization_record($saved,$initial_fail_run,$initial_fail_id)&&!nmkr_sync_finalization_handoff_pending($initial_fail_run,$initial_fail_id)&&nmkr_sync_owner_matches($initial_fail_run,'running',$initial_fail_id)&&get_option('nmkr_sync_status')==='finalization_error','initial handoff scheduling failure retains complete input and owner without executable pending claim');
$invalid_id=130;$invalid_run='34343434-3434-4434-8434-343434343434';active_run($invalid_id);$GLOBALS['options']['nmkr_sync_data']['run_id']=$invalid_run;$GLOBALS['owner']=array('run_id'=>$invalid_run,'mode'=>'direct','state'=>'finalizing','sync_stats_id'=>$invalid_id);$invalid=array('sync_stats_id'=>$invalid_id,'attempt'=>0,'metrics'=>$GLOBALS['final_metrics']);update_option(nmkr_sync_finalization_resume_key($invalid_id),$invalid,false);nmkr_schedule_sync_finalization_resume($invalid_id);$before=array(count($GLOBALS['metrics']),$GLOBALS['history'][$invalid_id],$GLOBALS['options']['nmkr_sync_data'],$GLOBALS['owner'],get_transient('nmkr_sync_progress'));check(nmkr_resume_sync_finalization($invalid_id)===false&&get_option(nmkr_sync_finalization_resume_key($invalid_id))===$invalid&&nmkr_sync_finalization_resume_event_scheduled($invalid_id)&&get_option('nmkr_sync_status')==='finalization_error'&&$before===array(count($GLOBALS['metrics']),$GLOBALS['history'][$invalid_id],$GLOBALS['options']['nmkr_sync_data'],$GLOBALS['owner'],get_transient('nmkr_sync_progress')),'canonical direct run rejects and retains invalid record without finalizer mutation');
$restore_id=131;$restore_run='56565656-5656-4656-8656-565656565656';owned_run($restore_id,$restore_run);$restore=nmkr_prepare_sync_finalization($restore_id,array_merge($GLOBALS['owned_final'],array('run_id'=>$restore_run)),nmkr_get_sync_data());nmkr_sync_data_complete(true,'',$restore,false,true);update_option(nmkr_sync_finalization_resume_key($restore_id),$restore,false);nmkr_schedule_sync_finalization_resume($restore_id);$GLOBALS['fail_cleanup']='hook:nmkr_resume_sync_finalization';check(nmkr_finish_ownerless_terminal_cleanup(nmkr_get_sync_data(),true,$restore)===false&&get_option('nmkr_sync_status')==='finalizing'&&get_transient('nmkr_sync_status')==='finalizing'&&nmkr_sync_finalization_resume_event_scheduled($restore_id),'successful ownerless restoration exposes consistent finalizing status');$GLOBALS['fail_cleanup']='option:'.nmkr_sync_finalization_resume_key($restore_id);$GLOBALS['fail_schedule']=true;check(nmkr_finish_ownerless_terminal_cleanup(nmkr_get_sync_data(),true,$restore)===false&&get_option('nmkr_sync_status')==='finalization_error'&&get_transient('nmkr_sync_status')==='finalization_error','failed ownerless restoration preserves finalization_error without overwrite');unset($GLOBALS['fail_cleanup'],$GLOBALS['fail_schedule']);
$maintain_id=132;$maintain_run='78787878-7878-4878-8878-787878787878';owned_run($maintain_id,$maintain_run);$GLOBALS['options']['nmkr_sync_data']['status']='finalizing';$wrong=nmkr_save_sync_finalization_resume($maintain_id,array_merge($GLOBALS['owned_final'],array('run_id'=>'89898989-8989-4989-8989-898989898989')));check(nmkr_maintain_sync_finalization_resume(nmkr_get_sync_data(),true)===false&&get_option('nmkr_sync_status')==='finalization_error'&&get_transient('nmkr_sync_status')==='finalization_error','exact finalizing maintenance rejects record mismatched to canonical run');$exact=nmkr_save_sync_finalization_resume($maintain_id,array_merge($GLOBALS['owned_final'],array('run_id'=>$maintain_run)));check(nmkr_maintain_sync_finalization_resume(nmkr_get_sync_data(),true)===true&&nmkr_sync_finalization_resume_event_scheduled($maintain_id),'exact finalizing maintenance schedules only exact resume callback');

// Explicit stopped/failed outcomes never share history compatibility or success artifacts.
$stopped_id=140;$stopped_run='14141414-1414-4414-8414-141414141414';owned_run($stopped_id,$stopped_run);unset($GLOBALS['hooks']['nmkr_execute_sync_background']);$before_metrics=count($GLOBALS['metrics']);$before_last=get_option('nmkr_last_sync_time','unchanged');$stopped=array_merge($GLOBALS['owned_final'],array('run_id'=>$stopped_run,'sync_stats_id'=>$stopped_id,'outcome'=>'stopped','attempt'=>0));$terminal=nmkr_sync_data_complete(false,'Stopped by synthetic test',$stopped,true,true);check(is_array($terminal)&&$terminal['status']==='stopped'&&$GLOBALS['history'][$stopped_id]['status']==='stopped','stopped finalization persists only stopped');check(count($GLOBALS['metrics'])===$before_metrics&&nmkr_get_sync_metrics_receipt($stopped_id)===false&&get_option('nmkr_last_sync_time','unchanged')===$before_last&&empty($terminal['error_code']),'stopped finalization writes no success metric receipt timestamp or failure code');update_option(nmkr_sync_finalization_resume_key($stopped_id),$stopped,false);nmkr_schedule_sync_finalization_resume($stopped_id);$GLOBALS['fail_cleanup']='hook:nmkr_resume_sync_finalization';check(nmkr_finish_ownerless_terminal_cleanup($terminal,'stopped',$stopped)===false&&get_option('nmkr_sync_status')==='finalizing'&&nmkr_sync_finalization_resume_pending($stopped_id),'ownerless stopped cleanup failure restores exact retry evidence');unset($GLOBALS['fail_cleanup']);check(nmkr_finish_ownerless_terminal_cleanup($terminal,'stopped',$stopped)===true&&get_option('nmkr_sync_data')['status']==='stopped','ownerless stopped cleanup is idempotent and remains stopped');
$failed_id=141;$failed_run='15151515-1515-4515-8515-151515151515';owned_run($failed_id,$failed_run);$failed=nmkr_prepare_sync_finalization($failed_id,array('run_id'=>$failed_run,'outcome'=>'failed'),nmkr_get_sync_data());$failed_terminal=nmkr_sync_data_complete(false,'Failed by synthetic test',$failed,true,true);check(is_array($failed_terminal)&&$failed_terminal['status']==='failed'&&$GLOBALS['history'][$failed_id]['status']==='failed','failed finalization persists only failed');check(nmkr_verify_sync_terminal_result($failed_terminal,'failed')&&nmkr_verify_sync_terminal_result($terminal,'stopped')&&!nmkr_verify_sync_terminal_result($failed_terminal,'stopped')&&!nmkr_verify_sync_terminal_result($terminal,'failed'),'matching failed and stopped direct terminal identities verify only their exact outcomes');
$rewritten_id=153;$rewritten_run='24242424-2424-4242-8242-242424242424';active_run($rewritten_id);$GLOBALS['options']['nmkr_sync_data']['run_id']=$rewritten_run;unset($GLOBALS['options']['nmkr_sync_data']['api_metric_evidence']);delete_transient('nmkr_current_sync_stats_live');$GLOBALS['history'][$rewritten_id]['run_id']=$rewritten_run;$GLOBALS['owner']=array('run_id'=>$rewritten_run,'mode'=>'direct','state'=>'running','sync_stats_id'=>$rewritten_id);$before_metrics=count($GLOBALS['metrics']);$before_last=get_option('nmkr_last_sync_time','unchanged');$rewritten=nmkr_prepare_sync_finalization($rewritten_id,array_merge($GLOBALS['owned_final'],array('run_id'=>$rewritten_run)),nmkr_get_sync_data());check(is_array($rewritten)&&$rewritten['outcome']==='failed'&&!isset($rewritten['metrics'])&&$rewritten['error_message']==='Completed synchronization metrics are unavailable.','missing completed metrics persist their bounded validation reason with the failed outcome');$transitioned=nmkr_transition_sync_owner($rewritten_run,'running','finalizing',$rewritten_id);$rewritten_terminal=nmkr_sync_data_complete(true,$rewritten['error_message'],$rewritten,false,true);check(nmkr_sync_owner_transition_succeeded($transitioned)&&is_array($rewritten_terminal)&&$rewritten_terminal['status']==='failed'&&$GLOBALS['history'][$rewritten_id]['status']==='failed'&&$GLOBALS['history'][$rewritten_id]['error_message']===$rewritten['error_message']&&get_option('nmkr_sync_error')===$rewritten['error_message']&&!get_option('nmkr_sync_in_progress')&&nmkr_get_sync_owner()===false,'prepared failed outcome immediately uses its persisted reason and clears active ownership');check(count($GLOBALS['metrics'])===$before_metrics&&nmkr_get_sync_metrics_receipt($rewritten_id)===false&&get_option('nmkr_last_sync_time','unchanged')===$before_last&&!nmkr_sync_finalization_resume_pending($rewritten_id),'rewritten failed outcome creates no success artifacts and requires no executable resume callback');
$resume_failed_id=154;$resume_failed_run='25252525-2525-4252-8252-252525252525';active_run($resume_failed_id);$GLOBALS['options']['nmkr_sync_data']['run_id']=$resume_failed_run;unset($GLOBALS['options']['nmkr_sync_data']['api_metric_evidence']);delete_transient('nmkr_current_sync_stats_live');$GLOBALS['history'][$resume_failed_id]['run_id']=$resume_failed_run;$GLOBALS['owner']=array('run_id'=>$resume_failed_run,'mode'=>'direct','state'=>'running','sync_stats_id'=>$resume_failed_id);$before_metrics=count($GLOBALS['metrics']);$before_last=get_option('nmkr_last_sync_time','unchanged');$resume_failed=nmkr_prepare_sync_finalization($resume_failed_id,array_merge($GLOBALS['owned_final'],array('run_id'=>$resume_failed_run)),nmkr_get_sync_data());unset($GLOBALS['hooks'][hook_key('nmkr_resume_sync_finalization',array($resume_failed_id))]);check(nmkr_resume_sync_finalization($resume_failed_id)===true&&$GLOBALS['history'][$resume_failed_id]['status']==='failed'&&$GLOBALS['history'][$resume_failed_id]['error_message']===$resume_failed['error_message']&&get_option('nmkr_sync_error')===$resume_failed['error_message'],'interrupted immediate finalization resumes with the same metrics-validation failure reason');check(count($GLOBALS['metrics'])===$before_metrics&&nmkr_get_sync_metrics_receipt($resume_failed_id)===false&&get_option('nmkr_last_sync_time','unchanged')===$before_last,'resumed metrics-validation failure creates no success receipt metrics or timestamp');
$stop_rewrite_id=155;$stop_rewrite_run='26262626-2626-4262-8262-262626262626';active_run($stop_rewrite_id);$GLOBALS['options']['nmkr_sync_data']['run_id']=$stop_rewrite_run;unset($GLOBALS['options']['nmkr_sync_data']['api_metric_evidence']);delete_transient('nmkr_current_sync_stats_live');$GLOBALS['history'][$stop_rewrite_id]['run_id']=$stop_rewrite_run;$GLOBALS['owner']=array('run_id'=>$stop_rewrite_run,'mode'=>'direct','state'=>'running','sync_stats_id'=>$stop_rewrite_id);$stop_rewrite=nmkr_prepare_sync_finalization($stop_rewrite_id,array_merge($GLOBALS['owned_final'],array('run_id'=>$stop_rewrite_run)),nmkr_get_sync_data());$GLOBALS['owner']['state']='stop_requested';unset($GLOBALS['hooks'][hook_key('nmkr_resume_sync_finalization',array($stop_rewrite_id))]);check(nmkr_resume_sync_finalization($stop_rewrite_id)===true&&get_option('nmkr_sync_data')['status']==='stopped'&&$GLOBALS['history'][$stop_rewrite_id]['status']==='stopped'&&$GLOBALS['history'][$stop_rewrite_id]['error_message']==='Synchronization stopped by user.'&&$GLOBALS['history'][$stop_rewrite_id]['error_message']!==$stop_rewrite['error_message']&&get_option('nmkr_sync_error',false)===false,'Stop-winning replacement discards the stale metrics-validation failure reason');
$stop_failure_id=142;$stop_failure_run='16161616-1616-4616-8616-161616161616';owned_run($stop_failure_id,$stop_failure_run);$GLOBALS['owner']['state']='stop_requested';$before_metrics=count($GLOBALS['metrics']);$before_writes=$GLOBALS['history'][$stop_failure_id]['writes'];$stop_terminal=nmkr_finalize_stop_winning_worker_failure($stop_failure_run,$stop_failure_id);check(is_array($stop_terminal)&&$stop_terminal['status']==='stopped'&&$GLOBALS['history'][$stop_failure_id]['status']==='stopped'&&$GLOBALS['history'][$stop_failure_id]['writes']===$before_writes+1&&count($GLOBALS['metrics'])===$before_metrics&&get_option('nmkr_sync_data')['status']==='stopped'&&nmkr_get_sync_owner()===false,'Stop-winning ordinary failure uses production decision helper to terminalize stopped without generic failed cleanup');$successor=array('run_id'=>'17171717-1717-4717-8717-171717171717','mode'=>'direct','state'=>'running','sync_stats_id'=>143);$GLOBALS['owner']=$successor;check(nmkr_finalize_stop_winning_worker_failure($stop_failure_run,$stop_failure_id)===false&&$GLOBALS['owner']===$successor,'Stop-winning helper never changes a mismatched successor owner');
$routed_stop_id=156;$routed_stop_run='27272727-2727-4272-8272-272727272727';active_run($routed_stop_id);$GLOBALS['options']['nmkr_sync_data']=array_merge($GLOBALS['options']['nmkr_sync_data'],array('run_id'=>$routed_stop_run,'items_processed'=>7,'items_successful'=>5,'items_failed'=>1,'items_skipped'=>1,'token_details_synced'=>4));$GLOBALS['history'][$routed_stop_id]['run_id']=$routed_stop_run;$GLOBALS['owner']=array('run_id'=>$routed_stop_run,'mode'=>'direct','state'=>'stop_requested','sync_stats_id'=>$routed_stop_id);$before_metrics=count($GLOBALS['metrics']);$before_last=get_option('nmkr_last_sync_time','unchanged');$GLOBALS['fail_history_update']=true;$routed_stop=nmkr_handle_direct_worker_error(new WP_Error('nmkr_api_metric_evidence_persistence_failure','Stale failure text must not survive Stop.'),$routed_stop_run,$routed_stop_id,array('items_processed'=>8,'items_successful'=>5,'items_failed'=>2,'items_skipped'=>1,'token_details_synced'=>4));$routed_stop_record=get_option(nmkr_sync_finalization_resume_key($routed_stop_id),false);check(is_wp_error($routed_stop)&&$routed_stop->get_error_code()==='sync_stopped_finalization_pending'&&nmkr_is_valid_sync_finalization_record($routed_stop_record,$routed_stop_run,$routed_stop_id)&&$routed_stop_record['outcome']==='stopped'&&!isset($routed_stop_record['error_message'])&&array($routed_stop_record['items_processed'],$routed_stop_record['items_successful'],$routed_stop_record['items_failed'],$routed_stop_record['items_skipped'],$routed_stop_record['token_details_synced'])===array(8,5,2,1,4)&&nmkr_sync_owner_matches($routed_stop_run,'finalizing',$routed_stop_id),'Stop-winning routed failure durably prepares exact valid counters without stale failed reason before interrupted finalization');unset($GLOBALS['fail_history_update']);unset($GLOBALS['hooks'][hook_key('nmkr_resume_sync_finalization',array($routed_stop_id))]);check(nmkr_resume_sync_finalization($routed_stop_id)===true&&get_option('nmkr_sync_data')['status']==='stopped'&&nmkr_get_sync_owner()===false&&!get_option('nmkr_sync_in_progress')&&count($GLOBALS['metrics'])===$before_metrics&&get_option('nmkr_last_sync_time','unchanged')===$before_last,'valid stopped resume reaches canonical cleanup without success artifacts or stranded finalizing state');
$stop_save_id=158;$stop_save_run='29292929-2929-4292-8292-292929292929';active_run($stop_save_id);$GLOBALS['options']['nmkr_sync_data']['run_id']=$stop_save_run;$GLOBALS['history'][$stop_save_id]['run_id']=$stop_save_run;$GLOBALS['owner']=array('run_id'=>$stop_save_run,'mode'=>'direct','state'=>'stop_requested','sync_stats_id'=>$stop_save_id);$GLOBALS['fail_cleanup']='option:'.nmkr_sync_finalization_resume_key($stop_save_id);$stop_save_failed=nmkr_handle_sync_worker_halt(new WP_Error('sync_stop_requested','Stop'),$stop_save_run,$stop_save_id,$GLOBALS['owned_final']);check(is_wp_error($stop_save_failed)&&$stop_save_failed->get_error_code()==='sync_stopped_finalization_pending'&&nmkr_sync_owner_matches($stop_save_run,'stop_requested',$stop_save_id)&&!nmkr_sync_finalization_resume_event_scheduled($stop_save_id),'stopped handoff save/readback failure occurs before owner transition');unset($GLOBALS['fail_cleanup']);
$stop_schedule_id=159;$stop_schedule_run='30303030-3030-4303-8303-303030303030';active_run($stop_schedule_id);$GLOBALS['options']['nmkr_sync_data']['run_id']=$stop_schedule_run;$GLOBALS['history'][$stop_schedule_id]['run_id']=$stop_schedule_run;$GLOBALS['owner']=array('run_id'=>$stop_schedule_run,'mode'=>'direct','state'=>'stop_requested','sync_stats_id'=>$stop_schedule_id);$GLOBALS['fail_schedule']=true;$stop_schedule_failed=nmkr_handle_sync_worker_halt(new WP_Error('sync_stop_requested','Stop'),$stop_schedule_run,$stop_schedule_id,$GLOBALS['owned_final']);$stop_schedule_record=get_option(nmkr_sync_finalization_resume_key($stop_schedule_id),false);check(is_wp_error($stop_schedule_failed)&&$stop_schedule_failed->get_error_code()==='sync_stopped_finalization_pending'&&nmkr_is_valid_sync_finalization_record($stop_schedule_record,$stop_schedule_run,$stop_schedule_id)&&nmkr_sync_owner_matches($stop_schedule_run,'stop_requested',$stop_schedule_id)&&!nmkr_sync_finalization_resume_event_scheduled($stop_schedule_id),'stopped handoff scheduling failure retains recoverable exact Stop before owner transition');unset($GLOBALS['fail_schedule']);
$halt_counter_id=160;$halt_counter_run='31313131-3131-4313-8313-313131313131';active_run($halt_counter_id);$GLOBALS['options']['nmkr_sync_data']['run_id']=$halt_counter_run;$GLOBALS['history'][$halt_counter_id]['run_id']=$halt_counter_run;$GLOBALS['owner']=array('run_id'=>$halt_counter_run,'mode'=>'direct','state'=>'stop_requested','sync_stats_id'=>$halt_counter_id);$GLOBALS['fail_history_update']=true;$halt_counters=array('items_processed'=>11,'items_successful'=>7,'items_failed'=>2,'items_skipped'=>2,'token_details_synced'=>6);$halt_counter_result=nmkr_handle_direct_worker_error(new WP_Error('sync_stop_requested','Stop'),$halt_counter_run,$halt_counter_id,$halt_counters);$halt_counter_record=get_option(nmkr_sync_finalization_resume_key($halt_counter_id),false);check(is_wp_error($halt_counter_result)&&array($halt_counter_record['items_processed'],$halt_counter_record['items_successful'],$halt_counter_record['items_failed'],$halt_counter_record['items_skipped'],$halt_counter_record['token_details_synced'])===array_values($halt_counters),'shared direct-worker Stop router forwards truthful live counters');unset($GLOBALS['fail_history_update']);

// A late exception must route the live in-scope counters into Stop finalization.
$core_catch=substr($core_source,strrpos($core_source,'} catch (Exception $e)'));
foreach(array('total_tokens','total_successful_tokens','total_failed_tokens','total_skipped_tokens','token_details_synced') as $live_counter){check(strpos($core_catch,"isset($".$live_counter.") ? $".$live_counter." : 0")!==false,'late catch Stop route forwards '.$live_counter);}
$late_stop_id=162;$late_stop_run='34343434-3434-4343-8343-343434343434';active_run($late_stop_id);$GLOBALS['options']['nmkr_sync_data']['run_id']=$late_stop_run;$GLOBALS['history'][$late_stop_id]['run_id']=$late_stop_run;$GLOBALS['owner']=array('run_id'=>$late_stop_run,'mode'=>'direct','state'=>'stop_requested','sync_stats_id'=>$late_stop_id);$late_counters=array('items_processed'=>13,'items_successful'=>8,'items_failed'=>3,'items_skipped'=>2,'token_details_synced'=>7);$late_metrics=count($GLOBALS['metrics']);$late_last=get_option('nmkr_last_sync_time','unchanged');$GLOBALS['fail_history_update']=true;$late_pending=nmkr_finalize_stop_winning_worker_failure($late_stop_run,$late_stop_id,$late_counters);$late_record=get_option(nmkr_sync_finalization_resume_key($late_stop_id),false);check(is_wp_error($late_pending)&&$late_record['outcome']==='stopped'&&array($late_record['items_processed'],$late_record['items_successful'],$late_record['items_failed'],$late_record['items_skipped'],$late_record['token_details_synced'])===array_values($late_counters),'late exception Stop remains authoritative and durably preserves exact non-zero counters');unset($GLOBALS['fail_history_update']);unset($GLOBALS['hooks'][hook_key('nmkr_resume_sync_finalization',array($late_stop_id))]);check(nmkr_resume_sync_finalization($late_stop_id)===true&&$GLOBALS['history'][$late_stop_id]['status']==='stopped'&&array($GLOBALS['history'][$late_stop_id]['items_processed'],$GLOBALS['history'][$late_stop_id]['items_successful'],$GLOBALS['history'][$late_stop_id]['items_failed'],$GLOBALS['history'][$late_stop_id]['items_skipped'],$GLOBALS['history'][$late_stop_id]['token_details_synced'])===array_values($late_counters)&&nmkr_get_sync_owner()===false&&!get_option('nmkr_sync_in_progress')&&count($GLOBALS['metrics'])===$late_metrics&&get_option('nmkr_last_sync_time','unchanged')===$late_last,'resumed late-exception Stop preserves counters and cleans up without success artifacts');$late_successor=array('run_id'=>'35353535-3535-4353-8353-353535353535','mode'=>'direct','state'=>'running','sync_stats_id'=>163);$GLOBALS['owner']=$late_successor;check(nmkr_finalize_stop_winning_worker_failure($late_stop_run,$late_stop_id,$late_counters)===false&&$GLOBALS['owner']===$late_successor,'late exception Stop route leaves a mismatched successor owner untouched');

// Bound ordinary failure writes a durable failed terminal before releasing only its exact owner.
$bound_fail_id=144;$bound_fail_run='18181818-1818-4818-8818-181818181818';owned_run($bound_fail_id,$bound_fail_run);$GLOBALS['owner']['state']='running';$before_metrics=count($GLOBALS['metrics']);$before_writes=$GLOBALS['history'][$bound_fail_id]['writes'];$bound_failed=nmkr_finalize_direct_worker_failure($bound_fail_run,$bound_fail_id,'Synthetic ordinary failure',$GLOBALS['owned_final']);check(is_array($bound_failed)&&$bound_failed['status']==='failed'&&get_option('nmkr_sync_data')['status']==='failed'&&get_option('nmkr_sync_data')['run_id']===$bound_fail_run&&$GLOBALS['history'][$bound_fail_id]['status']==='failed'&&$GLOBALS['history'][$bound_fail_id]['writes']===$before_writes+1&&count($GLOBALS['metrics'])===$before_metrics&&nmkr_get_sync_owner()===false,'bound ordinary failure preserves canonical failed terminal and releases only after exact finalization');
$routed_fail_id=157;$routed_fail_run='28282828-2828-4282-8282-282828282828';owned_run($routed_fail_id,$routed_fail_run);$GLOBALS['owner']['state']='running';$routed_reason="  Routed <b>database</b> failure\n".str_repeat('x',600);$expected_reason=nmkr_bound_sync_finalization_error_message($routed_reason);$GLOBALS['fail_history_update']=true;$routed_failed=nmkr_finalize_direct_worker_failure($routed_fail_run,$routed_fail_id,$routed_reason,array('items_failed'=>1));$routed_failed_record=get_option(nmkr_sync_finalization_resume_key($routed_fail_id),false);check(is_wp_error($routed_failed)&&$routed_failed_record['outcome']==='failed'&&$routed_failed_record['error_message']===$expected_reason&&strlen($routed_failed_record['error_message'])===500&&nmkr_is_valid_sync_finalization_record($routed_failed_record,$routed_fail_run,$routed_fail_id),'ordinary routed failure persists its bounded sanitized reason before interrupted terminalization');unset($GLOBALS['fail_history_update']);unset($GLOBALS['hooks'][hook_key('nmkr_resume_sync_finalization',array($routed_fail_id))]);check(nmkr_resume_sync_finalization($routed_fail_id)===true&&$GLOBALS['history'][$routed_fail_id]['error_message']===$expected_reason&&get_option('nmkr_sync_error')===$expected_reason&&nmkr_get_sync_owner()===false&&!get_option('nmkr_sync_in_progress'),'resumed routed failure preserves the same durable reason in history progress and canonical error state');
$utf8_fail_id=161;$utf8_fail_run='32323232-3232-4323-8323-323232323232';owned_run($utf8_fail_id,$utf8_fail_run);$GLOBALS['owner']['state']='running';$utf8_reason=str_repeat('a',499).'€ trailing';$utf8_expected=nmkr_bound_sync_finalization_error_message($utf8_reason);$GLOBALS['fail_history_update']=true;$utf8_failed=nmkr_finalize_direct_worker_failure($utf8_fail_run,$utf8_fail_id,$utf8_reason,array('items_failed'=>1));$utf8_record=get_option(nmkr_sync_finalization_resume_key($utf8_fail_id),false);check(is_wp_error($utf8_failed)&&strlen($utf8_expected)<=500&&preg_match('//u',$utf8_expected)===1&&$utf8_expected!==''&&$utf8_record['error_message']===$utf8_expected,'multibyte failure reason crossing byte bound remains valid UTF-8 and persists unchanged');unset($GLOBALS['fail_history_update']);unset($GLOBALS['hooks'][hook_key('nmkr_resume_sync_finalization',array($utf8_fail_id))]);check(nmkr_resume_sync_finalization($utf8_fail_id)===true&&$GLOBALS['history'][$utf8_fail_id]['error_message']===$utf8_expected&&get_option('nmkr_sync_error')===$utf8_expected,'UTF-8-safe bounded failure reason survives interruption and resume identically');
$write_run='abababab-abab-4bab-8bab-abababababab';active_run(146);$GLOBALS['options']['nmkr_sync_data']['run_id']=$write_run;$GLOBALS['history'][146]['run_id']=$write_run;$GLOBALS['owner']=array('run_id'=>$write_run,'mode'=>'direct','state'=>'running','sync_stats_id'=>146);$write_failure=nmkr_handle_direct_worker_error(new WP_Error('nmkr_token_write_failed','Synthetic write failure.'),$write_run,146,array('items_failed'=>1));check(is_array($write_failure)&&$write_failure['status']==='failed'&&!get_option('nmkr_sync_in_progress'),'persistence WP_Error enters canonical failed finalization');
$detail_run='acacacac-acac-4cac-8cac-acacacacacac';active_run(147);$GLOBALS['options']['nmkr_sync_data']['run_id']=$detail_run;$GLOBALS['history'][147]['run_id']=$detail_run;$GLOBALS['owner']=array('run_id'=>$detail_run,'mode'=>'direct','state'=>'running','sync_stats_id'=>147);$GLOBALS['token_detail_http_dispatches']=0;$GLOBALS['detail_post_request_checkpoints']=0;$GLOBALS['detail_request_mode']='checkpoint_failure';$detail_terminal=false;$detail_log=array();$detail_steps=0;foreach(array('synthetic-token-one','synthetic-token-two') as $detail_uid){$detail_result=nmkr_sync_token_details($detail_uid,'synthetic-project',$detail_log,$detail_steps,2,null,$detail_run,147);if(is_wp_error($detail_result)&&$detail_result->get_error_code()==='nmkr_api_metric_evidence_persistence_failure'){$detail_terminal=nmkr_handle_direct_worker_error($detail_result,$detail_run,147,array('items_processed'=>2,'items_failed'=>1));break;}}check($GLOBALS['token_detail_http_dispatches']===1&&$GLOBALS['detail_post_request_checkpoints']===0&&is_array($detail_terminal)&&$detail_terminal['status']==='failed'&&!get_option('nmkr_sync_in_progress')&&nmkr_get_sync_owner()===false,'token-detail evidence loss is not masked by a failing post-request checkpoint and uses canonical failed cleanup');
$stop_detail_run='acacacac-bcbc-4cac-8cac-acacacacacac';active_run(151);$GLOBALS['options']['nmkr_sync_data']['run_id']=$stop_detail_run;$GLOBALS['history'][151]['run_id']=$stop_detail_run;$GLOBALS['owner']=array('run_id'=>$stop_detail_run,'mode'=>'direct','state'=>'running','sync_stats_id'=>151);$GLOBALS['token_detail_http_dispatches']=0;$GLOBALS['detail_request_mode']='stop_wins';$before_metrics=count($GLOBALS['metrics']);$stop_detail_log=array();$stop_detail_steps=0;$stop_detail_result=nmkr_sync_token_details('synthetic-stop-token','synthetic-project',$stop_detail_log,$stop_detail_steps,1,null,$stop_detail_run,151);$stop_detail_terminal=nmkr_handle_sync_worker_halt($stop_detail_result,$stop_detail_run,151);check($GLOBALS['token_detail_http_dispatches']===1&&is_array($stop_detail_terminal)&&$stop_detail_terminal['status']==='stopped'&&count($GLOBALS['metrics'])===$before_metrics&&!get_option('nmkr_sync_in_progress')&&nmkr_get_sync_owner()===false,'in-flight token-detail Stop wins over evidence loss and terminalizes stopped without success metrics');
$GLOBALS['detail_request_mode']='';
$step_run='adadadad-adad-4dad-8dad-adadadadadad';active_run(148);$GLOBALS['options']['nmkr_sync_data']['run_id']=$step_run;$GLOBALS['history'][148]['run_id']=$step_run;$GLOBALS['owner']=array('run_id'=>$step_run,'mode'=>'direct','state'=>'running','sync_stats_id'=>148);$GLOBALS['token_list_http_dispatches']=0;$step_result=nmkr_count_sync_steps(array(array('uid'=>'project-one'),array('uid'=>'project-two')),$step_run,148);$step_terminal=is_wp_error($step_result)?nmkr_handle_direct_worker_error($step_result,$step_run,148):false;check($GLOBALS['token_list_http_dispatches']===1&&is_array($step_terminal)&&$step_terminal['status']==='failed'&&!get_option('nmkr_sync_in_progress')&&nmkr_get_sync_owner()===false,'step-count token-list evidence failure prevents the next project dispatch and uses canonical failed cleanup');
$project_run='aeaeaeae-aeae-4eae-8eae-aeaeaeaeaeae';active_run(149);$GLOBALS['options']['nmkr_sync_data']['run_id']=$project_run;$GLOBALS['history'][149]['run_id']=$project_run;$GLOBALS['owner']=array('run_id'=>$project_run,'mode'=>'direct','state'=>'running','sync_stats_id'=>149);$GLOBALS['project_http_dispatches']=0;$GLOBALS['token_list_http_dispatches']=0;$project_log=array();$project_steps=0;$project_result=nmkr_sync_projects($project_log,$project_steps,1,$project_run,149);$project_terminal=is_wp_error($project_result)?nmkr_handle_direct_worker_error($project_result,$project_run,149):false;if(!is_wp_error($project_result)){nmkr_connect_fetch_nfts_by_project('must-not-dispatch');}check($GLOBALS['project_http_dispatches']===1&&$GLOBALS['token_list_http_dispatches']===0&&is_array($project_terminal)&&$project_terminal['status']==='failed'&&!get_option('nmkr_sync_in_progress')&&nmkr_get_sync_owner()===false,'project-list evidence failure prevents token-list dispatch and uses canonical failed cleanup');
$stop_project_run='aeaeaeae-bebe-4eae-8eae-aeaeaeaeaeae';active_run(152);$GLOBALS['options']['nmkr_sync_data']['run_id']=$stop_project_run;$GLOBALS['history'][152]['run_id']=$stop_project_run;$GLOBALS['owner']=array('run_id'=>$stop_project_run,'mode'=>'direct','state'=>'running','sync_stats_id'=>152);$GLOBALS['project_http_dispatches']=0;$GLOBALS['token_list_http_dispatches']=0;$GLOBALS['project_request_mode']='stop_wins';$before_metrics=count($GLOBALS['metrics']);$stop_project_log=array();$stop_project_steps=0;$stop_project_result=nmkr_sync_projects($stop_project_log,$stop_project_steps,1,$stop_project_run,152);$stop_project_terminal=is_wp_error($stop_project_result)?nmkr_handle_direct_worker_error($stop_project_result,$stop_project_run,152):false;check($GLOBALS['project_http_dispatches']===1&&$GLOBALS['token_list_http_dispatches']===0&&is_array($stop_project_terminal)&&$stop_project_terminal['status']==='stopped'&&count($GLOBALS['metrics'])===$before_metrics&&!get_option('nmkr_sync_in_progress')&&nmkr_get_sync_owner()===false,'shared direct-worker router gives an in-flight project-list Stop precedence over evidence loss without later dispatch or success metrics');$GLOBALS['project_request_mode']='';
$token_run='afafafaf-afaf-4faf-8faf-afafafafafaf';active_run(150);$GLOBALS['options']['nmkr_sync_data']['run_id']=$token_run;$GLOBALS['history'][150]['run_id']=$token_run;$GLOBALS['owner']=array('run_id'=>$token_run,'mode'=>'direct','state'=>'running','sync_stats_id'=>150);$GLOBALS['token_list_http_dispatches']=0;$token_log=array();$token_terminal=false;foreach(array('project-one','project-two') as $token_project){$token_result=nmkr_fetch_tokens_for_project($token_project,$token_log,0,2,$token_run,150);if(is_wp_error($token_result)){$token_terminal=nmkr_handle_direct_worker_error($token_result,$token_run,150);break;}}check($GLOBALS['token_list_http_dispatches']===1&&is_array($token_terminal)&&$token_terminal['status']==='failed'&&!get_option('nmkr_sync_in_progress')&&nmkr_get_sync_owner()===false,'normal token-list evidence failure prevents the next project dispatch and uses canonical failed cleanup');
$blocked_fail_id=145;$blocked_fail_run='19191919-1919-4919-8919-191919191919';owned_run($blocked_fail_id,$blocked_fail_run);$GLOBALS['owner']['state']='running';$GLOBALS['fail_owner_release']=true;$blocked=nmkr_finalize_direct_worker_failure($blocked_fail_run,$blocked_fail_id,'Synthetic release failure',$GLOBALS['owned_final']);check(is_wp_error($blocked)&&nmkr_get_sync_owner()['run_id']===$blocked_fail_run&&get_option('nmkr_sync_data')['status']==='failed'&&nmkr_sync_finalization_resume_pending($blocked_fail_id),'failed owner release retains durable terminal recovery evidence and blocks unsafe admission');unset($GLOBALS['fail_owner_release']);
$successor=array('run_id'=>'20202020-2020-4020-8020-202020202020','mode'=>'direct','state'=>'running','sync_stats_id'=>146);$GLOBALS['owner']=$successor;check(nmkr_finalize_direct_worker_failure($bound_fail_run,$bound_fail_id,'stale')===false&&$GLOBALS['owner']===$successor,'bound failure finalizer never changes a successor owner');
$stale_error=new WP_Error('nmkr_api_metric_evidence_persistence_failure','Synthetic stale worker failure.');check(nmkr_handle_direct_worker_error($stale_error,$bound_fail_run,$bound_fail_id)===$stale_error&&$GLOBALS['owner']===$successor,'shared direct-worker router never changes a mismatched successor owner');

// A Stop before history binding publishes an ownerless stopped terminal and never strands the owner.
$pre_stop_run='21212121-2121-4212-8212-212121212121';active_run(0);$GLOBALS['options']['nmkr_sync_data']=array('status'=>'initializing','completed'=>false,'run_id'=>$pre_stop_run,'sync_stats_id'=>0);$GLOBALS['owner']=array('run_id'=>$pre_stop_run,'mode'=>'direct','state'=>'stop_requested','sync_stats_id'=>0);$GLOBALS['hooks'][hook_key('nmkr_execute_sync_background',array($pre_stop_run))]=1;$pre_stop=nmkr_finalize_pre_history_stop_on_early_failure($pre_stop_run);check(is_array($pre_stop)&&$pre_stop['outcome']==='stopped'&&get_option('nmkr_sync_data')['status']==='stopped'&&nmkr_get_sync_owner()===false&&!get_option('nmkr_sync_in_progress',false)&&wp_next_scheduled('nmkr_execute_sync_background',array($pre_stop_run))===false,'pre-history Stop cleanup releases exact owner, clears active work, and leaves a polling terminal');
$pre_successor=array('run_id'=>'22222222-2222-4222-8222-222222222222','mode'=>'direct','state'=>'running','sync_stats_id'=>147);$GLOBALS['owner']=$pre_successor;check(nmkr_finalize_pre_history_stop_on_early_failure($pre_stop_run)===false&&$GLOBALS['owner']===$pre_successor,'pre-history Stop cleanup never changes a mismatched successor');
$pre_fail_run='23232323-2323-4232-8232-232323232323';active_run(0);$GLOBALS['options']['nmkr_sync_data']=array('status'=>'initializing','completed'=>false,'run_id'=>$pre_fail_run,'sync_stats_id'=>0);$GLOBALS['owner']=array('run_id'=>$pre_fail_run,'mode'=>'direct','state'=>'stop_requested','sync_stats_id'=>0);$GLOBALS['fail_sync_data_save']=true;$pre_failed=nmkr_finalize_pre_history_stop_on_early_failure($pre_fail_run);check(is_wp_error($pre_failed)&&nmkr_get_sync_owner()['run_id']===$pre_fail_run&&get_option('nmkr_sync_status')==='stop_cleanup_error','pre-history Stop cleanup failure retains visible exact recovery evidence');unset($GLOBALS['fail_sync_data_save']);

echo "All terminalization regression checks passed.\n";
